# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""HTTP routes for service.department. Route handlers only delegate to the application service."""
from __future__ import annotations

from typing import Literal
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Response

from ...api_common import error_responses
from ...auth import authorize
from ...engine import ListQuery, Principal
from ..deps import get_services
from ...application.services import Services
from ..schemas.department import DepartmentCreateRequest, DepartmentResponse, DepartmentUpdateRequest


router = APIRouter(tags=["department"])


@router.get(
    "/departments",
    operation_id="api.department.list",
    summary="List Departments",
    description="List Departments.\n\nOperation `operation.department.list`. Access: restricted (employee, manager).",
    response_model=list[DepartmentResponse],
    status_code=200,
    responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=False, rate_limited=False),
)
def api_department_list(
    response: Response,
    limit: int = Query(100, ge=1, le=1000),
    offset: int = Query(0, ge=0),
    sort: str | None = Query(None, max_length=64, description="Attribute to sort by"),
    order: Literal['asc', 'desc'] = Query('asc'),
    principal: Principal | None = Depends(authorize("operation.department.list")),
    services: Services = Depends(get_services),
):
    page = services.department.list(principal, ListQuery(filters={}, search=None, sort=sort, order=order, limit=limit, offset=offset))
    response.headers['X-Total-Count'] = str(page.total)
    return page.items


@router.post(
    "/departments",
    operation_id="api.department.create",
    summary="Create Department",
    description="Create Department.\n\nOperation `operation.department.create`. Access: restricted (manager).",
    response_model=DepartmentResponse,
    status_code=201,
    responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=True, rate_limited=False),
)
def api_department_create(
    body: DepartmentCreateRequest,
    principal: Principal | None = Depends(authorize("operation.department.create")),
    services: Services = Depends(get_services),
):
    return services.department.create(principal, body)


@router.patch(
    "/departments/{id}",
    operation_id="api.department.update",
    summary="Update Department",
    description="Update Department.\n\nOperation `operation.department.update`. Access: restricted (manager).",
    response_model=DepartmentResponse,
    status_code=200,
    responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=True, rate_limited=False),
)
def api_department_update(
    id: UUID,
    body: DepartmentUpdateRequest,
    principal: Principal | None = Depends(authorize("operation.department.update")),
    services: Services = Depends(get_services),
):
    return services.department.update(principal, id, body)
