# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""HTTP routes for service.employee. Route handlers only delegate to the application service."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any, Literal
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Response

from ...api_common import error_responses
from ...auth import authorize
from ...engine import ListQuery, Principal
from ..deps import get_services
from ...application.services import Services
from ..schemas.employee import EmployeeCreateRequest, EmployeeResponse, EmployeeUpdateRequest

router = APIRouter(tags=["employee"])

@router.get("/employees", operation_id="api.employee.list", summary="List Employees", description="List Employees.\n\nOperation `operation.employee.list`. Access: restricted (manager).",
    response_model=list[EmployeeResponse], status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=False, rate_limited=False))
def api_employee_list(request: Request, response: Response, limit: int = Query(100, ge=1, le=1000), offset: int = Query(0, ge=0), sort: str | None = Query(None, max_length=64, description="Attribute to sort by"), order: Literal['asc', 'desc'] = Query('asc'), principal: Principal | None = Depends(authorize("operation.employee.list")), services: Services = Depends(get_services)):
    page = services.employee.list(principal, ListQuery(filters={}, search=None, sort=sort, order=order, limit=limit, offset=offset))
    response.headers['X-Total-Count'] = str(page.total)
    return page.items

@router.post("/employees", operation_id="api.employee.create", summary="Create Employee", description="Create Employee.\n\nOperation `operation.employee.create`. Access: restricted (manager).",
    response_model=EmployeeResponse, status_code=201, responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=True, rate_limited=False))
def api_employee_create(request: Request, body: EmployeeCreateRequest, principal: Principal | None = Depends(authorize("operation.employee.create")), services: Services = Depends(get_services)):
    return services.employee.create(principal, body)

@router.get("/employees/{id}", operation_id="api.employee.read", summary="View Employee", description="View Employee.\n\nOperation `operation.employee.read`. Access: restricted (employee, manager).",
    response_model=EmployeeResponse, status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=False, rate_limited=False))
def api_employee_read(request: Request, id: UUID, principal: Principal | None = Depends(authorize("operation.employee.read")), services: Services = Depends(get_services)):
    return services.employee.read(principal, id)

@router.patch("/employees/{id}", operation_id="api.employee.update", summary="Update Employee", description="Update Employee.\n\nOperation `operation.employee.update`. Access: restricted (manager).",
    response_model=EmployeeResponse, status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=True, rate_limited=False))
def api_employee_update(request: Request, id: UUID, body: EmployeeUpdateRequest, principal: Principal | None = Depends(authorize("operation.employee.update")), services: Services = Depends(get_services)):
    return services.employee.update(principal, id, body)

