# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""HTTP routes for service.project. Route handlers only delegate to the application service."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any, Literal
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Response

from ...api_common import error_responses
from ...auth import authorize
from ...engine import ListQuery, Principal
from ..deps import get_services
from ...application.services import Services
from ..schemas.project import ProjectCreateRequest, ProjectProgressResponse, ProjectResponse, ProjectUpdateRequest

router = APIRouter(tags=["project"])

@router.get("/projects", operation_id="api.project.list", summary="List Projects", description="List Projects.\n\nOperation `operation.project.list`. Access: restricted (employee, manager).",
    response_model=list[ProjectResponse], status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=False, rate_limited=False))
def api_project_list(request: Request, response: Response, limit: int = Query(100, ge=1, le=1000), offset: int = Query(0, ge=0), sort: str | None = Query(None, max_length=64, description="Attribute to sort by"), order: Literal['asc', 'desc'] = Query('asc'), principal: Principal | None = Depends(authorize("operation.project.list")), services: Services = Depends(get_services)):
    page = services.project.list(principal, ListQuery(filters={}, search=None, sort=sort, order=order, limit=limit, offset=offset))
    response.headers['X-Total-Count'] = str(page.total)
    return page.items

@router.post("/projects", operation_id="api.project.create", summary="Create Project", description="Create Project.\n\nOperation `operation.project.create`. Access: restricted (manager).",
    response_model=ProjectResponse, status_code=201, responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=True, rate_limited=False))
def api_project_create(request: Request, body: ProjectCreateRequest, principal: Principal | None = Depends(authorize("operation.project.create")), services: Services = Depends(get_services)):
    return services.project.create(principal, body)

@router.get("/projects/progress", operation_id="api.project.progress", summary="Get project progress", description="Task completion per project\n\nOperation `operation.project.progress`. Access: restricted (manager). Note: aggregate: the response schema is the plain entity list",
    response_model=list[ProjectProgressResponse], status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=False, rate_limited=False))
def api_project_progress(request: Request, response: Response, limit: int = Query(100, ge=1, le=1000), offset: int = Query(0, ge=0), sort: str | None = Query(None, max_length=64, description="Attribute to sort by"), order: Literal['asc', 'desc'] = Query('asc'), principal: Principal | None = Depends(authorize("operation.project.progress")), services: Services = Depends(get_services)):
    result = services.project.progress(principal, query=ListQuery(filters={}, sort=sort, order=order, limit=limit, offset=offset))
    items = result.items if hasattr(result, 'items') and not isinstance(result, dict) else result
    if hasattr(result, 'total'):
        response.headers['X-Total-Count'] = str(result.total)
    return items

@router.delete("/projects/{id}", operation_id="api.project.delete", summary="Delete Project", description="Delete Project.\n\nOperation `operation.project.delete`. Access: restricted (manager).",
    response_model=None, status_code=204, responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=True, rate_limited=False), response_class=Response)
def api_project_delete(request: Request, id: UUID, principal: Principal | None = Depends(authorize("operation.project.delete")), services: Services = Depends(get_services)):
    services.project.delete(principal, id)
    return Response(status_code=204)

@router.get("/projects/{id}", operation_id="api.project.read", summary="View Project", description="View Project.\n\nOperation `operation.project.read`. Access: restricted (employee, manager).",
    response_model=ProjectResponse, status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=False, rate_limited=False))
def api_project_read(request: Request, id: UUID, principal: Principal | None = Depends(authorize("operation.project.read")), services: Services = Depends(get_services)):
    return services.project.read(principal, id)

@router.patch("/projects/{id}", operation_id="api.project.update", summary="Update Project", description="Update Project.\n\nOperation `operation.project.update`. Access: restricted (manager).",
    response_model=ProjectResponse, status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=True, rate_limited=False))
def api_project_update(request: Request, id: UUID, body: ProjectUpdateRequest, principal: Principal | None = Depends(authorize("operation.project.update")), services: Services = Depends(get_services)):
    return services.project.update(principal, id, body)

