# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""HTTP routes for service.task. Route handlers only delegate to the application service."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any, Literal
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Response

from ...api_common import error_responses
from ...auth import authorize
from ...engine import ListQuery, Principal
from ..deps import get_services
from ...application.services import Services
from ..schemas.task import TaskCreateRequest, TaskResponse, TaskUpdateRequest, TaskUpdateStatusRequest

router = APIRouter(tags=["task"])

@router.get("/tasks", operation_id="api.task.list", summary="List Tasks", description="List Tasks.\n\nOperation `operation.task.list`. Access: restricted (employee, manager).",
    response_model=list[TaskResponse], status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=False, rate_limited=False))
def api_task_list(request: Request, response: Response, limit: int = Query(100, ge=1, le=1000), offset: int = Query(0, ge=0), sort: str | None = Query(None, max_length=64, description="Attribute to sort by"), order: Literal['asc', 'desc'] = Query('asc'), principal: Principal | None = Depends(authorize("operation.task.list")), services: Services = Depends(get_services)):
    page = services.task.list(principal, ListQuery(filters={}, search=None, sort=sort, order=order, limit=limit, offset=offset))
    response.headers['X-Total-Count'] = str(page.total)
    return page.items

@router.post("/tasks", operation_id="api.task.create", summary="Create Task", description="Create Task.\n\nOperation `operation.task.create`. Access: restricted (manager).",
    response_model=TaskResponse, status_code=201, responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=True, rate_limited=False))
def api_task_create(request: Request, body: TaskCreateRequest, principal: Principal | None = Depends(authorize("operation.task.create")), services: Services = Depends(get_services)):
    return services.task.create(principal, body)

@router.get("/tasks/assigned", operation_id="api.task.list_assigned", summary="List my assigned tasks", description="List my assigned tasks.\n\nOperation `operation.task.list_assigned`. Access: restricted (employee).",
    response_model=list[TaskResponse], status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=False, rate_limited=False))
def api_task_list_assigned(request: Request, response: Response, limit: int = Query(100, ge=1, le=1000), offset: int = Query(0, ge=0), sort: str | None = Query(None, max_length=64, description="Attribute to sort by"), order: Literal['asc', 'desc'] = Query('asc'), principal: Principal | None = Depends(authorize("operation.task.list_assigned")), services: Services = Depends(get_services)):
    page = services.task.list_assigned(principal, ListQuery(filters={}, search=None, sort=sort, order=order, limit=limit, offset=offset))
    response.headers['X-Total-Count'] = str(page.total)
    return page.items

@router.delete("/tasks/{id}", operation_id="api.task.delete", summary="Delete Task", description="Delete Task.\n\nOperation `operation.task.delete`. Access: restricted (manager).",
    response_model=None, status_code=204, responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=True, rate_limited=False), response_class=Response)
def api_task_delete(request: Request, id: UUID, principal: Principal | None = Depends(authorize("operation.task.delete")), services: Services = Depends(get_services)):
    services.task.delete(principal, id)
    return Response(status_code=204)

@router.get("/tasks/{id}", operation_id="api.task.read", summary="View Task", description="View Task.\n\nOperation `operation.task.read`. Access: restricted (employee, manager).",
    response_model=TaskResponse, status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=False, rate_limited=False))
def api_task_read(request: Request, id: UUID, principal: Principal | None = Depends(authorize("operation.task.read")), services: Services = Depends(get_services)):
    return services.task.read(principal, id)

@router.patch("/tasks/{id}", operation_id="api.task.update", summary="Update Task", description="Update Task.\n\nOperation `operation.task.update`. Access: restricted (manager).",
    response_model=TaskResponse, status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=True, rate_limited=False))
def api_task_update(request: Request, id: UUID, body: TaskUpdateRequest, principal: Principal | None = Depends(authorize("operation.task.update")), services: Services = Depends(get_services)):
    return services.task.update(principal, id, body)

@router.patch("/tasks/{id}/status", operation_id="api.task.update_status", summary="Update task status", description="Update task status.\n\nOperation `operation.task.update_status`. Access: restricted (employee, manager).",
    response_model=TaskResponse, status_code=200, responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=True, rate_limited=False))
def api_task_update_status(request: Request, id: UUID, body: TaskUpdateStatusRequest, principal: Principal | None = Depends(authorize("operation.task.update_status")), services: Services = Depends(get_services)):
    return services.task.update_status(principal, id, body)

