# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Checkout workflow (operation.order.place): totals, stock, cart, atomicity, concurrency. Real PostgreSQL."""
import threading
import uuid
from decimal import Decimal

import pytest

from backend_app.engine import Principal
from backend_app.errors import ConflictError

pytestmark = pytest.mark.integration
PATH = '/orders'
BODY = {'shipping_address': '1 Main Street', 'payment_method': 'sample'}


def _cart(world, user, qty, stock, price="10.00"):
    product = world.insert('entity.product', price=Decimal(price), stock=stock)
    world.insert('entity.cart_item', **{'user_id': user["id"], 'product_id': product["id"], "quantity": qty})
    return product


def _happy_path(world):
    user = world.user('customer')
    p1, p2 = _cart(world, user, 2, 5, "10.00"), _cart(world, user, 1, 3, "4.50")
    r = world.client.post(PATH, json=BODY, headers=world.headers(user))
    assert r.status_code == 201, r.text
    order = world.get('entity.order', uuid.UUID(r.json()["id"]))
    assert order['user_id'] == user["id"], "the order belongs to the caller"
    assert order["total"] == Decimal("24.50"), "total = sum(price * quantity)"
    lines = [row for row in world.rows('entity.order_item') if row['order_id'] == order["id"]]
    assert len(lines) == 2 and sorted(l["quantity"] for l in lines) == [1, 2]
    assert {l["unit_price"] for l in lines} == {Decimal("10.00"), Decimal("4.50")}, "unit prices are frozen at order time"
    assert world.get('entity.product', p1["id"])["stock"] == 3 and world.get('entity.product', p2["id"])["stock"] == 2
    assert [r for r in world.rows('entity.cart_item') if r['user_id'] == user["id"]] == [], "the cart is emptied"


def _empty_cart(world):
    user = world.user('customer')
    before = world.dump()
    r = world.client.post(PATH, json=BODY, headers=world.headers(user))
    assert r.status_code == 409 and r.json()["error"]["code"] == 'CART_EMPTY', r.text
    assert world.dump() == before, "no data is changed"


def _insufficient_stock(world):
    user = world.user('customer')
    ok = _cart(world, user, 1, 5)
    short = _cart(world, user, 3, 2)  # second line cannot be fulfilled
    before = world.dump()
    r = world.client.post(PATH, json=BODY, headers=world.headers(user))
    assert r.status_code == 409 and r.json()["error"]["code"] == 'OUT_OF_STOCK', r.text
    assert world.dump() == before, "no order, no lines, no stock change, cart intact: the transaction rolled back as a whole"
    assert world.get('entity.product', ok["id"])["stock"] == 5


def test_placing_an_order_creates_lines_decrements_stock_and_empties_the_cart(world):
    _happy_path(world)


def test_an_empty_cart_cannot_be_ordered(world):
    _empty_cart(world)


def test_insufficient_stock_rolls_everything_back(world):
    _insufficient_stock(world)


def test_other_customers_carts_are_untouched(world):
    a, b = world.user('customer'), world.user('customer')
    _cart(world, a, 1, 5)
    pb = _cart(world, b, 1, 5)
    assert world.client.post(PATH, json=BODY, headers=world.headers(a)).status_code == 201
    assert [r for r in world.rows('entity.cart_item') if r['user_id'] == b["id"]], "the other customer's cart must survive"
    assert world.get('entity.product', pb["id"])["stock"] == 5


def test_concurrent_checkouts_never_oversell(world):
    a, b = world.user('customer'), world.user('customer')
    product = world.insert('entity.product', price=Decimal("10.00"), stock=1)
    for u in (a, b):
        world.insert('entity.cart_item', **{'user_id': u["id"], 'product_id': product["id"], "quantity": 1})
    service = world.container.services.order
    results = []

    def go(u):
        p = Principal(u["id"], u["email"], u["role"], "role." + u["role"], frozenset({"role." + u["role"]}))
        try:
            service.place(p, body=dict(BODY))
            results.append("ok")
        except ConflictError:
            results.append("conflict")

    threads = [threading.Thread(target=go, args=(u,)) for u in (a, b)]
    [t.start() for t in threads]
    [t.join(20) for t in threads]
    assert sorted(results) == ["conflict", "ok"], results
    assert world.get('entity.product', product["id"])["stock"] == 0
    assert len(world.rows('entity.order')) == 1


def test_ac_ac_order_cart_not_empty(world):
    """ac.order.cart_not_empty: Given the user is signed in When the customer checks out with an empty cart Then The cart is empty (error CART_EMPTY) no data is changed"""
    _empty_cart(world)


def test_ac_ac_order_checkout(world):
    """ac.order.checkout: Given the user is signed in as Customer When Enter shipping address and payment method and Place order Then The order is placed and its details are shown"""
    _happy_path(world)


def test_ac_ac_product_stock_available(world):
    """ac.product.stock_available: Given the user is signed in When the customer orders more units than are in stock Then One or more products are out of stock (error OUT_OF_STOCK) no data is changed"""
    _insufficient_stock(world)
