DROP FUNCTION IF EXISTS create_department(text, text);
CREATE FUNCTION create_department(p_name text, p_description text) RETURNS departments LANGUAGE sql AS $$ INSERT INTO departments (name, description) VALUES (p_name, p_description) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_department(uuid);
CREATE FUNCTION get_department(p_id uuid) RETURNS SETOF departments LANGUAGE sql AS $$ SELECT * FROM departments WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_department(uuid, text, text);
CREATE FUNCTION update_department(p_id uuid, p_name text, p_description text) RETURNS departments LANGUAGE plpgsql AS $$ DECLARE r departments; BEGIN UPDATE departments SET name = p_name, description = p_description WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'department % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_department(uuid);
CREATE FUNCTION delete_department(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM departments WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_departments();
CREATE FUNCTION list_departments() RETURNS SETOF departments LANGUAGE sql AS $$ SELECT * FROM departments ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_user(text, text, text, text, timestamptz);
CREATE FUNCTION create_user(p_email text, p_password_hash text, p_full_name text, p_role text, p_created_at timestamptz) RETURNS users LANGUAGE sql AS $$ INSERT INTO users (email, password_hash, full_name, role, created_at) VALUES (p_email, p_password_hash, p_full_name, p_role, p_created_at) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_user(uuid);
CREATE FUNCTION get_user(p_id uuid) RETURNS SETOF users LANGUAGE sql AS $$ SELECT * FROM users WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_user(uuid, text, text, text, text, timestamptz);
CREATE FUNCTION update_user(p_id uuid, p_email text, p_password_hash text, p_full_name text, p_role text, p_created_at timestamptz) RETURNS users LANGUAGE plpgsql AS $$ DECLARE r users; BEGIN UPDATE users SET email = p_email, password_hash = p_password_hash, full_name = p_full_name, role = p_role, created_at = p_created_at WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'user % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_user(uuid);
CREATE FUNCTION delete_user(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM users WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_users();
CREATE FUNCTION list_users() RETURNS SETOF users LANGUAGE sql AS $$ SELECT * FROM users ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_employee(uuid, uuid, text);
CREATE FUNCTION create_employee(p_user_id uuid, p_department_id uuid, p_job_title text) RETURNS employees LANGUAGE sql AS $$ INSERT INTO employees (user_id, department_id, job_title) VALUES (p_user_id, p_department_id, p_job_title) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_employee(uuid);
CREATE FUNCTION get_employee(p_id uuid) RETURNS SETOF employees LANGUAGE sql AS $$ SELECT * FROM employees WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_employee(uuid, uuid, uuid, text);
CREATE FUNCTION update_employee(p_id uuid, p_user_id uuid, p_department_id uuid, p_job_title text) RETURNS employees LANGUAGE plpgsql AS $$ DECLARE r employees; BEGIN UPDATE employees SET user_id = p_user_id, department_id = p_department_id, job_title = p_job_title WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'employee % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_employee(uuid);
CREATE FUNCTION delete_employee(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM employees WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_employees();
CREATE FUNCTION list_employees() RETURNS SETOF employees LANGUAGE sql AS $$ SELECT * FROM employees ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_project(text, text, text, uuid, date);
CREATE FUNCTION create_project(p_name text, p_description text, p_status text, p_owner_id uuid, p_due_date date) RETURNS projects LANGUAGE sql AS $$ INSERT INTO projects (name, description, status, owner_id, due_date) VALUES (p_name, p_description, p_status, p_owner_id, p_due_date) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_project(uuid);
CREATE FUNCTION get_project(p_id uuid) RETURNS SETOF projects LANGUAGE sql AS $$ SELECT * FROM projects WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_project(uuid, text, text, text, uuid, date);
CREATE FUNCTION update_project(p_id uuid, p_name text, p_description text, p_status text, p_owner_id uuid, p_due_date date) RETURNS projects LANGUAGE plpgsql AS $$ DECLARE r projects; BEGIN UPDATE projects SET name = p_name, description = p_description, status = p_status, owner_id = p_owner_id, due_date = p_due_date WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'project % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_project(uuid);
CREATE FUNCTION delete_project(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM projects WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_projects();
CREATE FUNCTION list_projects() RETURNS SETOF projects LANGUAGE sql AS $$ SELECT * FROM projects ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_project_member(uuid, uuid);
CREATE FUNCTION create_project_member(p_project_id uuid, p_user_id uuid) RETURNS project_members LANGUAGE sql AS $$ INSERT INTO project_members (project_id, user_id) VALUES (p_project_id, p_user_id) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_project_member(uuid);
CREATE FUNCTION get_project_member(p_id uuid) RETURNS SETOF project_members LANGUAGE sql AS $$ SELECT * FROM project_members WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_project_member(uuid, uuid, uuid);
CREATE FUNCTION update_project_member(p_id uuid, p_project_id uuid, p_user_id uuid) RETURNS project_members LANGUAGE plpgsql AS $$ DECLARE r project_members; BEGIN UPDATE project_members SET project_id = p_project_id, user_id = p_user_id WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'project_member % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_project_member(uuid);
CREATE FUNCTION delete_project_member(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM project_members WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_project_members();
CREATE FUNCTION list_project_members() RETURNS SETOF project_members LANGUAGE sql AS $$ SELECT * FROM project_members ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_task(text, text, text, date, uuid, uuid);
CREATE FUNCTION create_task(p_title text, p_description text, p_status text, p_due_date date, p_project_id uuid, p_assignee_id uuid) RETURNS tasks LANGUAGE sql AS $$ INSERT INTO tasks (title, description, status, due_date, project_id, assignee_id) VALUES (p_title, p_description, p_status, p_due_date, p_project_id, p_assignee_id) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_task(uuid);
CREATE FUNCTION get_task(p_id uuid) RETURNS SETOF tasks LANGUAGE sql AS $$ SELECT * FROM tasks WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_task(uuid, text, text, text, date, uuid, uuid);
CREATE FUNCTION update_task(p_id uuid, p_title text, p_description text, p_status text, p_due_date date, p_project_id uuid, p_assignee_id uuid) RETURNS tasks LANGUAGE plpgsql AS $$ DECLARE r tasks; BEGIN UPDATE tasks SET title = p_title, description = p_description, status = p_status, due_date = p_due_date, project_id = p_project_id, assignee_id = p_assignee_id WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'task % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_task(uuid);
CREATE FUNCTION delete_task(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM tasks WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_tasks();
CREATE FUNCTION list_tasks() RETURNS SETOF tasks LANGUAGE sql AS $$ SELECT * FROM tasks ORDER BY id; $$;
