# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application services container."""
from __future__ import annotations

from ...service_base import ServiceContext
from .department_service import DepartmentService
from .employee_service import EmployeeService
from .project_service import ProjectService
from .project_member_service import ProjectMemberService
from .task_service import TaskService
from .user_service import UserService


class Services:
    """One attribute per graph service."""

    def __init__(self, ctx: ServiceContext) -> None:
        self.department = DepartmentService(ctx)
        self.employee = EmployeeService(ctx)
        self.project = ProjectService(ctx)
        self.project_member = ProjectMemberService(ctx)
        self.task = TaskService(ctx)
        self.user = UserService(ctx)


def build_services(ctx: ServiceContext) -> Services:
    return Services(ctx)
