# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application service service.department: one method per graph operation."""
from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Any
from uuid import UUID

from psycopg import sql

from ...engine import ListQuery, Page, Principal
from ...errors import (ConflictError, EntityNotFound, PermissionDenied, ValidationError)
from ...service_base import BaseService
from ...domain.entities.department import Department
from ...api.schemas.department import DepartmentCreateRequest, DepartmentUpdateRequest


class DepartmentService(BaseService):
    """Operations of service.department. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""

    def create(self, principal: Principal | None, body: DepartmentCreateRequest) -> Department:
        """operation.department.create (POST /departments) - create"""
        row = self.engine.run("operation.department.create", principal, body=body.model_dump(exclude_unset=True))
        return Department.model_validate(row)

    def list(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.department.list (GET /departments) - list"""
        page = self.engine.run("operation.department.list", principal, query=query)
        return Page([Department.model_validate(r) for r in page.items], page.total)

    def update(self, principal: Principal | None, row_id: UUID, body: DepartmentUpdateRequest) -> Department:
        """operation.department.update (PATCH /departments/{id}) - update"""
        row = self.engine.run("operation.department.update", principal, row_id=row_id, body=body.model_dump(exclude_unset=True))
        return Department.model_validate(row)

