# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application service service.employee: one method per graph operation."""
from __future__ import annotations

from uuid import UUID

from ...engine import ListQuery, Page, Principal
from ...service_base import BaseService
from ...domain.entities.employee import Employee
from ...api.schemas.employee import EmployeeCreateRequest, EmployeeUpdateRequest


class EmployeeService(BaseService):
    """Operations of service.employee. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""

    def create(self, principal: Principal | None, body: EmployeeCreateRequest) -> Employee:
        """operation.employee.create (POST /employees) - create"""
        row = self.engine.run("operation.employee.create", principal, body=body.model_dump(exclude_unset=True))
        return Employee.model_validate(row)

    def list(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.employee.list (GET /employees) - list"""
        page = self.engine.run("operation.employee.list", principal, query=query)
        return Page([Employee.model_validate(r) for r in page.items], page.total)

    def read(self, principal: Principal | None, row_id: UUID) -> Employee:
        """operation.employee.read (GET /employees/{id}) - read"""
        return Employee.model_validate(self.engine.run("operation.employee.read", principal, row_id=row_id))

    def update(self, principal: Principal | None, row_id: UUID, body: EmployeeUpdateRequest) -> Employee:
        """operation.employee.update (PATCH /employees/{id}) - update"""
        row = self.engine.run("operation.employee.update", principal, row_id=row_id, body=body.model_dump(exclude_unset=True))
        return Employee.model_validate(row)

