# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application service service.project_member: one method per graph operation."""
from __future__ import annotations

from uuid import UUID

from ...engine import ListQuery, Page, Principal
from ...service_base import BaseService
from ...domain.entities.project_member import ProjectMember
from ...api.schemas.project_member import ProjectMemberCreateRequest


class ProjectMemberService(BaseService):
    """Operations of service.project_member. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""

    def create(self, principal: Principal | None, body: ProjectMemberCreateRequest) -> ProjectMember:
        """operation.project_member.create (POST /project-members) - create"""
        row = self.engine.run("operation.project_member.create", principal, body=body.model_dump(exclude_unset=True))
        return ProjectMember.model_validate(row)

    def delete(self, principal: Principal | None, row_id: UUID) -> None:
        """operation.project_member.delete (DELETE /project-members/{id}) - delete"""
        self.engine.run("operation.project_member.delete", principal, row_id=row_id)

    def list(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.project_member.list (GET /project-members) - list"""
        page = self.engine.run("operation.project_member.list", principal, query=query)
        return Page([ProjectMember.model_validate(r) for r in page.items], page.total)

