# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application service service.project: one method per graph operation."""
from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Any
from uuid import UUID

from psycopg import sql

from ...engine import ListQuery, Page, Principal
from ...errors import (ConflictError, EntityNotFound, PermissionDenied, ValidationError)
from ...service_base import BaseService
from ...domain.entities.project import Project
from ...api.schemas.project import ProjectCreateRequest, ProjectUpdateRequest


class ProjectService(BaseService):
    """Operations of service.project. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""

    def create(self, principal: Principal | None, body: ProjectCreateRequest) -> Project:
        """operation.project.create (POST /projects) - create"""
        row = self.engine.run("operation.project.create", principal, body=body.model_dump(exclude_unset=True))
        return Project.model_validate(row)

    def delete(self, principal: Principal | None, row_id: UUID) -> None:
        """operation.project.delete (DELETE /projects/{id}) - delete"""
        self.engine.run("operation.project.delete", principal, row_id=row_id)

    def list(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.project.list (GET /projects) - list"""
        page = self.engine.run("operation.project.list", principal, query=query)
        return Page([Project.model_validate(r) for r in page.items], page.total)

    def progress(self, principal: Principal | None, *, row_id: UUID | None = None, body: dict[str, Any] | None = None, query: ListQuery | None = None) -> Any:
        """operation.project.progress (GET /projects/progress) - aggregate"""
        # handler source: llm (api_implementation)
        with self.db.transaction() as conn:
            rows = conn.execute('SELECT p.*, COALESCE(c.total, 0) AS task_count, COALESCE(c.done, 0) AS completed_task_count FROM "projects" p LEFT JOIN (SELECT "project_id" AS parent_id, count(*) AS total, count(*) FILTER (WHERE "status" = %s) AS done FROM "tasks" GROUP BY "project_id") c ON c.parent_id = p.id ORDER BY p.id', ('completed',)).fetchall()
        result = []
        for row in rows:
            total, completed = row["task_count"], row["completed_task_count"]
            row["progress_percent"] = int(round(100 * completed / total)) if total else 0
            result.append(row)
        return result

    def read(self, principal: Principal | None, row_id: UUID) -> Project:
        """operation.project.read (GET /projects/{id}) - read"""
        return Project.model_validate(self.engine.run("operation.project.read", principal, row_id=row_id))

    def update(self, principal: Principal | None, row_id: UUID, body: ProjectUpdateRequest) -> Project:
        """operation.project.update (PATCH /projects/{id}) - update"""
        row = self.engine.run("operation.project.update", principal, row_id=row_id, body=body.model_dump(exclude_unset=True))
        return Project.model_validate(row)

