# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application service service.task: one method per graph operation."""
from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Any
from uuid import UUID

from psycopg import sql

from ...engine import ListQuery, Page, Principal
from ...errors import (ConflictError, EntityNotFound, PermissionDenied, ValidationError)
from ...service_base import BaseService
from ...domain.entities.task import Task
from ...api.schemas.task import TaskCreateRequest, TaskUpdateRequest, TaskUpdateStatusRequest


class TaskService(BaseService):
    """Operations of service.task. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""

    def create(self, principal: Principal | None, body: TaskCreateRequest) -> Task:
        """operation.task.create (POST /tasks) - create"""
        row = self.engine.run("operation.task.create", principal, body=body.model_dump(exclude_unset=True))
        return Task.model_validate(row)

    def delete(self, principal: Principal | None, row_id: UUID) -> None:
        """operation.task.delete (DELETE /tasks/{id}) - delete"""
        self.engine.run("operation.task.delete", principal, row_id=row_id)

    def list(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.task.list (GET /tasks) - list"""
        page = self.engine.run("operation.task.list", principal, query=query)
        return Page([Task.model_validate(r) for r in page.items], page.total)

    def list_assigned(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.task.list_assigned (GET /tasks/assigned) - list"""
        page = self.engine.run("operation.task.list_assigned", principal, query=query)
        return Page([Task.model_validate(r) for r in page.items], page.total)

    def read(self, principal: Principal | None, row_id: UUID) -> Task:
        """operation.task.read (GET /tasks/{id}) - read"""
        return Task.model_validate(self.engine.run("operation.task.read", principal, row_id=row_id))

    def update(self, principal: Principal | None, row_id: UUID, body: TaskUpdateRequest) -> Task:
        """operation.task.update (PATCH /tasks/{id}) - update"""
        row = self.engine.run("operation.task.update", principal, row_id=row_id, body=body.model_dump(exclude_unset=True))
        return Task.model_validate(row)

    def update_status(self, principal: Principal | None, row_id: UUID, body: TaskUpdateStatusRequest) -> Task:
        """operation.task.update_status (PATCH /tasks/{id}/status) - transition"""
        row = self.engine.run("operation.task.update_status", principal, row_id=row_id, body=body.model_dump(exclude_unset=True))
        return Task.model_validate(row)

