DROP FUNCTION IF EXISTS create_user(text, text, text, text, timestamptz);
CREATE FUNCTION create_user(p_email text, p_password_hash text, p_full_name text, p_role text, p_created_at timestamptz) RETURNS users LANGUAGE sql AS $$ INSERT INTO users (email, password_hash, full_name, role, created_at) VALUES (p_email, p_password_hash, p_full_name, p_role, p_created_at) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_user(uuid);
CREATE FUNCTION get_user(p_id uuid) RETURNS SETOF users LANGUAGE sql AS $$ SELECT * FROM users WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_user(uuid, text, text, text, text, timestamptz);
CREATE FUNCTION update_user(p_id uuid, p_email text, p_password_hash text, p_full_name text, p_role text, p_created_at timestamptz) RETURNS users LANGUAGE plpgsql AS $$ DECLARE r users; BEGIN UPDATE users SET email = p_email, password_hash = p_password_hash, full_name = p_full_name, role = p_role, created_at = p_created_at WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'user % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_user(uuid);
CREATE FUNCTION delete_user(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM users WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_users();
CREATE FUNCTION list_users() RETURNS SETOF users LANGUAGE sql AS $$ SELECT * FROM users ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_ticket(text, text, text, text, uuid, uuid, timestamptz);
CREATE FUNCTION create_ticket(p_title text, p_description text, p_status text, p_priority text, p_requester_id uuid, p_assignee_id uuid, p_created_at timestamptz) RETURNS tickets LANGUAGE sql AS $$ INSERT INTO tickets (title, description, status, priority, requester_id, assignee_id, created_at) VALUES (p_title, p_description, p_status, p_priority, p_requester_id, p_assignee_id, p_created_at) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_ticket(uuid);
CREATE FUNCTION get_ticket(p_id uuid) RETURNS SETOF tickets LANGUAGE sql AS $$ SELECT * FROM tickets WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_ticket(uuid, text, text, text, text, uuid, uuid, timestamptz);
CREATE FUNCTION update_ticket(p_id uuid, p_title text, p_description text, p_status text, p_priority text, p_requester_id uuid, p_assignee_id uuid, p_created_at timestamptz) RETURNS tickets LANGUAGE plpgsql AS $$ DECLARE r tickets; BEGIN UPDATE tickets SET title = p_title, description = p_description, status = p_status, priority = p_priority, requester_id = p_requester_id, assignee_id = p_assignee_id, created_at = p_created_at WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'ticket % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_ticket(uuid);
CREATE FUNCTION delete_ticket(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM tickets WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_tickets();
CREATE FUNCTION list_tickets() RETURNS SETOF tickets LANGUAGE sql AS $$ SELECT * FROM tickets ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_ticket_comment(uuid, uuid, text, timestamptz);
CREATE FUNCTION create_ticket_comment(p_ticket_id uuid, p_author_id uuid, p_body text, p_created_at timestamptz) RETURNS ticket_comments LANGUAGE sql AS $$ INSERT INTO ticket_comments (ticket_id, author_id, body, created_at) VALUES (p_ticket_id, p_author_id, p_body, p_created_at) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_ticket_comment(uuid);
CREATE FUNCTION get_ticket_comment(p_id uuid) RETURNS SETOF ticket_comments LANGUAGE sql AS $$ SELECT * FROM ticket_comments WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_ticket_comment(uuid, uuid, uuid, text, timestamptz);
CREATE FUNCTION update_ticket_comment(p_id uuid, p_ticket_id uuid, p_author_id uuid, p_body text, p_created_at timestamptz) RETURNS ticket_comments LANGUAGE plpgsql AS $$ DECLARE r ticket_comments; BEGIN UPDATE ticket_comments SET ticket_id = p_ticket_id, author_id = p_author_id, body = p_body, created_at = p_created_at WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'ticket_comment % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_ticket_comment(uuid);
CREATE FUNCTION delete_ticket_comment(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM ticket_comments WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_ticket_comments();
CREATE FUNCTION list_ticket_comments() RETURNS SETOF ticket_comments LANGUAGE sql AS $$ SELECT * FROM ticket_comments ORDER BY id; $$;
