# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Aggregate (operation.project.progress): per-parent counts and percentage computed in the database."""
import pytest

pytestmark = pytest.mark.integration
PATH = '/projects/progress'


def test_progress_reports_completed_over_total_per_parent(world):
    boss = world.user('manager')
    p1, p2 = world.insert('entity.project'), world.insert('entity.project')
    world.insert('entity.task', **{'project_id': p1["id"], 'status': 'completed'})
    world.insert('entity.task', **{'project_id': p1["id"]})
    r = world.client.get(PATH, headers=world.headers(boss))
    assert r.status_code == 200, r.text
    by_id = {x["id"]: x for x in r.json()}
    a, b = by_id[str(p1["id"])], by_id[str(p2["id"])]
    assert (a['task_count'], a['completed_task_count'], a["progress_percent"]) == (2, 1, 50)
    assert (b['task_count'], b['completed_task_count'], b["progress_percent"]) == (0, 0, 0)
    assert "password_hash" not in r.text
