# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""HTTP routes for service.ticket. Route handlers only delegate to the application service."""
from __future__ import annotations

from typing import Literal
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Response

from ...api_common import error_responses
from ...auth import authorize
from ...engine import ListQuery, Principal
from ..deps import get_services
from ...application.services import Services
from ..schemas.ticket import TicketAssignRequest, TicketChangeStatusRequest, TicketCreateRequest, TicketResponse, TicketUpdateRequest


router = APIRouter(tags=["ticket"])


@router.get(
    "/tickets",
    operation_id="api.ticket.list",
    summary="List Tickets",
    description="List Tickets.\n\nOperation `operation.ticket.list`. Access: restricted (agent, customer, manager).",
    response_model=list[TicketResponse],
    status_code=200,
    responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=False, rate_limited=False),
)
def api_ticket_list(
    response: Response,
    limit: int = Query(100, ge=1, le=1000),
    offset: int = Query(0, ge=0),
    sort: str | None = Query(None, max_length=64, description="Attribute to sort by"),
    order: Literal['asc', 'desc'] = Query('asc'),
    principal: Principal | None = Depends(authorize("operation.ticket.list")),
    services: Services = Depends(get_services),
):
    page = services.ticket.list(principal, ListQuery(filters={}, search=None, sort=sort, order=order, limit=limit, offset=offset))
    response.headers['X-Total-Count'] = str(page.total)
    return page.items


@router.post(
    "/tickets",
    operation_id="api.ticket.create",
    summary="Create Ticket",
    description="Create Ticket.\n\nOperation `operation.ticket.create`. Access: restricted (customer).",
    response_model=TicketResponse,
    status_code=201,
    responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=True, rate_limited=False),
)
def api_ticket_create(
    body: TicketCreateRequest,
    principal: Principal | None = Depends(authorize("operation.ticket.create")),
    services: Services = Depends(get_services),
):
    return services.ticket.create(principal, body)


@router.get(
    "/tickets/stats",
    operation_id="api.ticket.stats",
    summary="Get ticket statistics",
    description="Get ticket statistics.\n\nOperation `operation.ticket.stats`. Access: restricted (manager). Note: aggregate: the response schema is the plain entity list",
    response_model=list[TicketResponse],
    status_code=200,
    responses=error_responses(authenticated=True, restricted=True, has_path_id=False, mutating=False, rate_limited=False),
)
def api_ticket_stats(
    response: Response,
    limit: int = Query(100, ge=1, le=1000),
    offset: int = Query(0, ge=0),
    sort: str | None = Query(None, max_length=64, description="Attribute to sort by"),
    order: Literal['asc', 'desc'] = Query('asc'),
    principal: Principal | None = Depends(authorize("operation.ticket.stats")),
    services: Services = Depends(get_services),
):
    result = services.ticket.stats(principal, query=ListQuery(filters={}, sort=sort, order=order, limit=limit, offset=offset))
    items = result.items if hasattr(result, 'items') and not isinstance(result, dict) else result
    if hasattr(result, 'total'):
        response.headers['X-Total-Count'] = str(result.total)
    return items


@router.get(
    "/tickets/{id}",
    operation_id="api.ticket.read",
    summary="View Ticket",
    description="View Ticket.\n\nOperation `operation.ticket.read`. Access: restricted (agent, customer, manager).",
    response_model=TicketResponse,
    status_code=200,
    responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=False, rate_limited=False),
)
def api_ticket_read(
    id: UUID,
    principal: Principal | None = Depends(authorize("operation.ticket.read")),
    services: Services = Depends(get_services),
):
    return services.ticket.read(principal, id)


@router.patch(
    "/tickets/{id}",
    operation_id="api.ticket.update",
    summary="Update Ticket",
    description="Update Ticket.\n\nOperation `operation.ticket.update`. Access: restricted (agent, manager).",
    response_model=TicketResponse,
    status_code=200,
    responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=True, rate_limited=False),
)
def api_ticket_update(
    id: UUID,
    body: TicketUpdateRequest,
    principal: Principal | None = Depends(authorize("operation.ticket.update")),
    services: Services = Depends(get_services),
):
    return services.ticket.update(principal, id, body)


@router.patch(
    "/tickets/{id}/assignee",
    operation_id="api.ticket.assign",
    summary="Assign ticket",
    description="Assign ticket.\n\nOperation `operation.ticket.assign`. Access: restricted (manager).",
    response_model=TicketResponse,
    status_code=200,
    responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=True, rate_limited=False),
)
def api_ticket_assign(
    id: UUID,
    body: TicketAssignRequest,
    principal: Principal | None = Depends(authorize("operation.ticket.assign")),
    services: Services = Depends(get_services),
):
    return services.ticket.assign(principal, id, body)


@router.patch(
    "/tickets/{id}/status",
    operation_id="api.ticket.change_status",
    summary="Change ticket status",
    description="Change ticket status.\n\nOperation `operation.ticket.change_status`. Access: restricted (agent, manager).",
    response_model=TicketResponse,
    status_code=200,
    responses=error_responses(authenticated=True, restricted=True, has_path_id=True, mutating=True, rate_limited=False),
)
def api_ticket_change_status(
    id: UUID,
    body: TicketChangeStatusRequest,
    principal: Principal | None = Depends(authorize("operation.ticket.change_status")),
    services: Services = Depends(get_services),
):
    return services.ticket.change_status(principal, id, body)
