# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity TicketComment (graph: entity.ticket_comment; table: ticket_comments)."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field



class TicketComment(BaseModel):
    """Row of `ticket_comments` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    ticket_id: UUID
    author_id: UUID
    body: str
    created_at: datetime | None = None

    TABLE: ClassVar[str] = "ticket_comments"
    GRAPH_ENTITY: ClassVar[str] = "entity.ticket_comment"
