# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity Ticket (graph: entity.ticket; table: tickets)."""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class TicketStatus(str, Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    RESOLVED = "resolved"
    CLOSED = "closed"

class TicketPriority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class Ticket(BaseModel):
    """Row of `tickets` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    title: str
    description: str
    status: TicketStatus
    priority: TicketPriority
    requester_id: UUID
    assignee_id: UUID | None = None
    created_at: datetime | None = None

    TABLE: ClassVar[str] = "tickets"
    GRAPH_ENTITY: ClassVar[str] = "entity.ticket"
