# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""API request/response models for entity.ticket (from api.json schemas)."""
from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class TicketResponse(BaseModel):
    """schema.ticket: Ticket"""

    model_config = ConfigDict(from_attributes=True)
    id: UUID
    title: str
    description: str
    status: Literal['open', 'in_progress', 'resolved', 'closed']
    priority: Literal['low', 'medium', 'high', 'urgent']
    requester_id: UUID
    assignee_id: UUID | None = None
    created_at: datetime | None = None


class TicketAssignRequest(BaseModel):
    """schema.ticket.assign: Assign ticket request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    assignee_id: UUID


class TicketChangeStatusRequest(BaseModel):
    """schema.ticket.change_status: Change ticket status request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    status: Literal['open', 'in_progress', 'resolved', 'closed']


class TicketCreateRequest(BaseModel):
    """schema.ticket.create: Create Ticket request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    title: str = Field(..., max_length=255, min_length=1)
    description: str = Field(..., max_length=20000, min_length=1)
    priority: Literal['low', 'medium', 'high', 'urgent']
    requester_id: UUID | None = Field(None, json_schema_extra={'readOnly': True, 'x-server-owned': True})


class TicketUpdateRequest(BaseModel):
    """schema.ticket.update: Update Ticket request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    title: str = Field(None, max_length=255, min_length=1)
    description: str = Field(None, max_length=20000, min_length=1)
    priority: Literal['low', 'medium', 'high', 'urgent'] = Field(None)
