# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""API request/response models for entity.ticket_comment (from api.json schemas)."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, EmailStr, Field

from ...api_common import JsonDecimal



class TicketCommentResponse(BaseModel):
    """schema.ticket_comment: Ticket Comment"""

    model_config = ConfigDict(from_attributes=True)
    id: UUID
    ticket_id: UUID
    author_id: UUID
    body: str
    created_at: datetime | None = None


class TicketCommentCreateRequest(BaseModel):
    """schema.ticket_comment.create: Create Comment request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    ticket_id: UUID
    body: str = Field(..., max_length=20000, min_length=1)
    author_id: UUID | None = Field(None, json_schema_extra={'readOnly': True, 'x-server-owned': True})
