# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""FastAPI dependencies."""
from __future__ import annotations

from fastapi import Request

from ..application.services import Services


def get_services(request: Request) -> Services:
    return request.app.state.container.services
