# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""All routers combined into one, routes ordered most-specific first.

FastAPI matches in registration order, so `/tasks/assigned` must precede `/tasks/{id}`; sorting globally guarantees it."""
from __future__ import annotations

from fastapi import APIRouter

from .cart_item import router as cart_item_router
from .order import router as order_router
from .product import router as product_router
from .user import router as user_router


def _key(route) -> tuple:
    segs = route.path.strip("/").split("/")
    return tuple((1, '') if s.startswith('{') else (0, s) for s in segs)


api_router = APIRouter()
_routes = [r for rt in [cart_item_router, order_router, product_router, user_router] for r in rt.routes]
api_router.routes.extend(sorted(_routes, key=lambda r: (_key(r), sorted(getattr(r, 'methods', []) or []))))

ROUTERS = [api_router]
