# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application services container."""
from __future__ import annotations

from ...service_base import ServiceContext
from .ticket_service import TicketService
from .ticket_comment_service import TicketCommentService
from .user_service import UserService


class Services:
    """One attribute per graph service."""

    def __init__(self, ctx: ServiceContext) -> None:
        self.ticket = TicketService(ctx)
        self.ticket_comment = TicketCommentService(ctx)
        self.user = UserService(ctx)


def build_services(ctx: ServiceContext) -> Services:
    return Services(ctx)
