# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application service service.ticket_comment: one method per graph operation."""
from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Any
from uuid import UUID

from psycopg import sql

from ...engine import ListQuery, Page, Principal
from ...errors import (ConflictError, EntityNotFound, PermissionDenied, ValidationError)
from ...service_base import BaseService
from ...domain.entities.ticket_comment import TicketComment
from ...api.schemas.ticket_comment import TicketCommentCreateRequest


class TicketCommentService(BaseService):
    """Operations of service.ticket_comment. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""

    def create(self, principal: Principal | None, body: TicketCommentCreateRequest) -> TicketComment:
        """operation.ticket_comment.create (POST /ticket-comments) - create"""
        row = self.engine.run("operation.ticket_comment.create", principal, body=body.model_dump(exclude_unset=True))
        return TicketComment.model_validate(row)

    def list(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.ticket_comment.list (GET /ticket-comments) - list"""
        page = self.engine.run("operation.ticket_comment.list", principal, query=query)
        return Page([TicketComment.model_validate(r) for r in page.items], page.total)

