# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application service service.ticket: one method per graph operation."""
from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Any
from uuid import UUID

from psycopg import sql

from ...engine import ListQuery, Page, Principal
from ...errors import (ConflictError, EntityNotFound, PermissionDenied, ValidationError)
from ...service_base import BaseService
from ...domain.entities.ticket import Ticket
from ...api.schemas.ticket import TicketAssignRequest, TicketChangeStatusRequest, TicketCreateRequest, TicketUpdateRequest


class TicketService(BaseService):
    """Operations of service.ticket. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""

    def assign(self, principal: Principal | None, row_id: UUID, body: TicketAssignRequest) -> Ticket:
        """operation.ticket.assign (PATCH /tickets/{id}/assignee) - update"""
        row = self.engine.run("operation.ticket.assign", principal, row_id=row_id, body=body.model_dump(exclude_unset=True))
        return Ticket.model_validate(row)

    def change_status(self, principal: Principal | None, row_id: UUID, body: TicketChangeStatusRequest) -> Ticket:
        """operation.ticket.change_status (PATCH /tickets/{id}/status) - transition"""
        row = self.engine.run("operation.ticket.change_status", principal, row_id=row_id, body=body.model_dump(exclude_unset=True))
        return Ticket.model_validate(row)

    def create(self, principal: Principal | None, body: TicketCreateRequest) -> Ticket:
        """operation.ticket.create (POST /tickets) - create"""
        row = self.engine.run("operation.ticket.create", principal, body=body.model_dump(exclude_unset=True))
        return Ticket.model_validate(row)

    def list(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.ticket.list (GET /tickets) - list"""
        page = self.engine.run("operation.ticket.list", principal, query=query)
        return Page([Ticket.model_validate(r) for r in page.items], page.total)

    def read(self, principal: Principal | None, row_id: UUID) -> Ticket:
        """operation.ticket.read (GET /tickets/{id}) - read"""
        return Ticket.model_validate(self.engine.run("operation.ticket.read", principal, row_id=row_id))

    def stats(self, principal: Principal | None, *, row_id: UUID | None = None, body: dict[str, Any] | None = None, query: ListQuery | None = None) -> Any:
        """operation.ticket.stats (GET /tickets/stats) - aggregate"""
        return self.not_implemented("operation.ticket.stats")

    def update(self, principal: Principal | None, row_id: UUID, body: TicketUpdateRequest) -> Ticket:
        """operation.ticket.update (PATCH /tickets/{id}) - update"""
        row = self.engine.run("operation.ticket.update", principal, row_id=row_id, body=body.model_dump(exclude_unset=True))
        return Ticket.model_validate(row)

