# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application service service.user: one method per graph operation."""
from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Any
from uuid import UUID

from psycopg import sql

from ...engine import ListQuery, Page, Principal
from ...errors import (ConflictError, EntityNotFound, PermissionDenied, ValidationError)
from ...service_base import BaseService
from ...domain.entities.user import User
from ...api.schemas.user import UserLoginRequest, UserRequestPasswordResetRequest, UserResetPasswordRequest


class UserService(BaseService):
    """Operations of service.user. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""

    def list_agents(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.user.list_agents (GET /users/agents) - list"""
        page = self.engine.run("operation.user.list_agents", principal, query=query)
        return Page([User.model_validate(r) for r in page.items], page.total)

    def login(self, body: UserLoginRequest, client: str) -> dict[str, Any]:
        """operation.user.login (POST /auth/login) - auth.login"""
        return self.ctx.auth.login(body.email, body.password, client)

    def logout(self, principal: Principal) -> None:
        """operation.user.logout (POST /auth/logout) - auth.logout"""
        self.ctx.auth.logout(principal)

    def request_password_reset(self, body: UserRequestPasswordResetRequest, client: str) -> None:
        """operation.user.request_password_reset (POST /auth/forgot-password) - auth.request_password_reset"""
        self.ctx.auth.request_password_reset(body.email, client)

    def reset_password(self, body: UserResetPasswordRequest, client: str) -> None:
        """operation.user.reset_password (POST /auth/reset-password) - auth.reset_password"""
        self.ctx.auth.reset_password(body.reset_token, body.new_password, client)

