# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""API request/response models for entity.department (from api.json schemas)."""
from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class DepartmentResponse(BaseModel):
    """schema.department: Department"""

    model_config = ConfigDict(from_attributes=True)
    id: UUID
    name: str
    description: str | None = None


class DepartmentCreateRequest(BaseModel):
    """schema.department.create: Create Department request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    name: str = Field(..., max_length=255, min_length=1)
    description: str = Field(..., max_length=20000, min_length=1)


class DepartmentUpdateRequest(BaseModel):
    """schema.department.update: Update Department request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    name: str = Field(None, max_length=255, min_length=1)
    description: str | None = Field(None, max_length=20000)
