# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""API request/response models for entity.employee (from api.json schemas)."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, EmailStr, Field

from ...api_common import JsonDecimal



class EmployeeResponse(BaseModel):
    """schema.employee: Employee"""

    model_config = ConfigDict(from_attributes=True)
    id: UUID
    user_id: UUID
    department_id: UUID | None = None
    job_title: str | None = None


class EmployeeCreateRequest(BaseModel):
    """schema.employee.create: Create Employee request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    user_id: UUID
    department_id: UUID
    job_title: str = Field(..., max_length=255, min_length=1)


class EmployeeUpdateRequest(BaseModel):
    """schema.employee.update: Update Employee request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    user_id: UUID = Field(None)
    department_id: UUID | None = Field(None)
    job_title: str | None = Field(None, max_length=255, min_length=1)
