# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""API request/response models for entity.project (from api.json schemas)."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, EmailStr, Field

from ...api_common import JsonDecimal



class ProjectResponse(BaseModel):
    """schema.project: Project"""

    model_config = ConfigDict(from_attributes=True)
    id: UUID
    name: str
    description: str | None = None
    status: Literal['planned', 'active', 'completed']
    owner_id: UUID | None = None
    due_date: date | None = None


class ProjectCreateRequest(BaseModel):
    """schema.project.create: Create Project request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    name: str = Field(..., max_length=255, min_length=1)
    description: str = Field(..., max_length=20000)
    owner_id: UUID | None = Field(None, json_schema_extra={'readOnly': True, 'x-server-owned': True})


class ProjectUpdateRequest(BaseModel):
    """schema.project.update: Update Project request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    name: str = Field(None, max_length=255, min_length=1)
    description: str | None = Field(None, max_length=20000)
    status: Literal['planned', 'active', 'completed'] = Field(None)
    due_date: date | None = Field(None)


class ProjectProgressResponse(ProjectResponse):
    """operation.project.progress: additive aggregate fields on top of the graph schema."""

    task_count: int | None = None
    completed_task_count: int | None = None
    progress_percent: int | None = None
