# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""API request/response models for entity.project_member (from api.json schemas)."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, EmailStr, Field

from ...api_common import JsonDecimal



class ProjectMemberResponse(BaseModel):
    """schema.project_member: Project Member"""

    model_config = ConfigDict(from_attributes=True)
    id: UUID
    project_id: UUID
    user_id: UUID


class ProjectMemberCreateRequest(BaseModel):
    """schema.project_member.create: Create Project Member request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    project_id: UUID
    user_id: UUID
