# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""API request/response models for entity.task (from api.json schemas)."""
from __future__ import annotations

from datetime import date
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class TaskResponse(BaseModel):
    """schema.task: Task"""

    model_config = ConfigDict(from_attributes=True)
    id: UUID
    title: str
    description: str | None = None
    status: Literal['todo', 'in_progress', 'completed']
    due_date: date | None = None
    project_id: UUID
    assignee_id: UUID | None = None


class TaskCreateRequest(BaseModel):
    """schema.task.create: Create Task request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    title: str = Field(..., max_length=255, min_length=1)
    project_id: UUID


class TaskUpdateRequest(BaseModel):
    """schema.task.update: Update Task request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    title: str = Field(None, max_length=255, min_length=1)
    description: str | None = Field(None, max_length=20000)
    due_date: date | None = Field(None)


class TaskUpdateStatusRequest(BaseModel):
    """schema.task.update_status: Update task status request"""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    status: Literal['todo', 'in_progress', 'completed']
