# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""API request/response models for entity.category (from api.json schemas)."""
from __future__ import annotations
