# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity Department (graph: entity.department; table: departments)."""
from __future__ import annotations

from typing import ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Department(BaseModel):
    """Row of `departments` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    name: str
    description: str | None = None

    TABLE: ClassVar[str] = "departments"
    GRAPH_ENTITY: ClassVar[str] = "entity.department"
