# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity Employee (graph: entity.employee; table: employees)."""
from __future__ import annotations

from typing import ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Employee(BaseModel):
    """Row of `employees` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    user_id: UUID
    department_id: UUID | None = None
    job_title: str | None = None

    TABLE: ClassVar[str] = "employees"
    GRAPH_ENTITY: ClassVar[str] = "entity.employee"
