# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity Employee (graph: entity.employee; table: employees)."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field



class Employee(BaseModel):
    """Row of `employees` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    user_id: UUID
    department_id: UUID | None = None
    job_title: str | None = None

    TABLE: ClassVar[str] = "employees"
    GRAPH_ENTITY: ClassVar[str] = "entity.employee"
