# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity Project (graph: entity.project; table: projects)."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ProjectStatus(str, Enum):
    PLANNED = "planned"
    ACTIVE = "active"
    COMPLETED = "completed"


class Project(BaseModel):
    """Row of `projects` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    name: str
    description: str | None = None
    status: ProjectStatus
    owner_id: UUID | None = None
    due_date: date | None = None

    TABLE: ClassVar[str] = "projects"
    GRAPH_ENTITY: ClassVar[str] = "entity.project"
