# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity ProjectMember (graph: entity.project_member; table: project_members)."""
from __future__ import annotations

from typing import ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class ProjectMember(BaseModel):
    """Row of `project_members` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    project_id: UUID
    user_id: UUID

    TABLE: ClassVar[str] = "project_members"
    GRAPH_ENTITY: ClassVar[str] = "entity.project_member"
