# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity Task (graph: entity.task; table: tasks)."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class TaskStatus(str, Enum):
    TODO = "todo"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"


class Task(BaseModel):
    """Row of `tasks` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    title: str
    description: str | None = None
    status: TaskStatus
    due_date: date | None = None
    project_id: UUID
    assignee_id: UUID | None = None

    TABLE: ClassVar[str] = "tasks"
    GRAPH_ENTITY: ClassVar[str] = "entity.task"
