# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity User (graph: entity.user; table: users)."""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class UserRole(str, Enum):
    MANAGER = "manager"
    EMPLOYEE = "employee"


class User(BaseModel):
    """Row of `users` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    email: str
    password_hash: str = Field(..., repr=False, exclude=True)
    full_name: str
    role: UserRole
    created_at: datetime

    TABLE: ClassVar[str] = "users"
    GRAPH_ENTITY: ClassVar[str] = "entity.user"
