# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository registry."""
from __future__ import annotations

from .cart_item_repository import CartItemRepository
from .category_repository import CategoryRepository
from .order_repository import OrderRepository
from .order_item_repository import OrderItemRepository
from .product_repository import ProductRepository
from .user_repository import UserRepository


REPOSITORIES = {
    "entity.cart_item": CartItemRepository,
    "entity.category": CategoryRepository,
    "entity.order": OrderRepository,
    "entity.order_item": OrderItemRepository,
    "entity.product": ProductRepository,
    "entity.user": UserRepository,
}
