# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.cart_item over table `cart_items` (database contract)."""
from ...repository import BaseRepository


class CartItemRepository(BaseRepository):
    ENTITY_ID = "entity.cart_item"
    TABLE = "cart_items"
