# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.category over table `categories` (database contract)."""
from ...repository import BaseRepository


class CategoryRepository(BaseRepository):
    ENTITY_ID = "entity.category"
    TABLE = "categories"
