# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.order over table `orders` (database contract)."""
from ...repository import BaseRepository


class OrderRepository(BaseRepository):
    ENTITY_ID = "entity.order"
    TABLE = "orders"
