# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.order_item over table `order_items` (database contract)."""
from ...repository import BaseRepository


class OrderItemRepository(BaseRepository):
    ENTITY_ID = "entity.order_item"
    TABLE = "order_items"
