# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.product over table `products` (database contract)."""
from ...repository import BaseRepository


class ProductRepository(BaseRepository):
    ENTITY_ID = "entity.product"
    TABLE = "products"
