DROP FUNCTION IF EXISTS create_category(text);
CREATE FUNCTION create_category(p_name text) RETURNS categories LANGUAGE sql AS $$ INSERT INTO categories (name) VALUES (p_name) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_category(uuid);
CREATE FUNCTION get_category(p_id uuid) RETURNS SETOF categories LANGUAGE sql AS $$ SELECT * FROM categories WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_category(uuid, text);
CREATE FUNCTION update_category(p_id uuid, p_name text) RETURNS categories LANGUAGE plpgsql AS $$ DECLARE r categories; BEGIN UPDATE categories SET name = p_name WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'category % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_category(uuid);
CREATE FUNCTION delete_category(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM categories WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_categories();
CREATE FUNCTION list_categories() RETURNS SETOF categories LANGUAGE sql AS $$ SELECT * FROM categories ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_product(text, text, numeric(12,2), integer, uuid, text);
CREATE FUNCTION create_product(p_name text, p_description text, p_price numeric(12,2), p_stock integer, p_category_id uuid, p_image_url text) RETURNS products LANGUAGE sql AS $$ INSERT INTO products (name, description, price, stock, category_id, image_url) VALUES (p_name, p_description, p_price, p_stock, p_category_id, p_image_url) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_product(uuid);
CREATE FUNCTION get_product(p_id uuid) RETURNS SETOF products LANGUAGE sql AS $$ SELECT * FROM products WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_product(uuid, text, text, numeric(12,2), integer, uuid, text);
CREATE FUNCTION update_product(p_id uuid, p_name text, p_description text, p_price numeric(12,2), p_stock integer, p_category_id uuid, p_image_url text) RETURNS products LANGUAGE plpgsql AS $$ DECLARE r products; BEGIN UPDATE products SET name = p_name, description = p_description, price = p_price, stock = p_stock, category_id = p_category_id, image_url = p_image_url WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'product % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_product(uuid);
CREATE FUNCTION delete_product(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM products WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_products();
CREATE FUNCTION list_products() RETURNS SETOF products LANGUAGE sql AS $$ SELECT * FROM products ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_user(text, text, text, text, timestamptz);
CREATE FUNCTION create_user(p_email text, p_password_hash text, p_full_name text, p_role text, p_created_at timestamptz) RETURNS users LANGUAGE sql AS $$ INSERT INTO users (email, password_hash, full_name, role, created_at) VALUES (p_email, p_password_hash, p_full_name, p_role, p_created_at) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_user(uuid);
CREATE FUNCTION get_user(p_id uuid) RETURNS SETOF users LANGUAGE sql AS $$ SELECT * FROM users WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_user(uuid, text, text, text, text, timestamptz);
CREATE FUNCTION update_user(p_id uuid, p_email text, p_password_hash text, p_full_name text, p_role text, p_created_at timestamptz) RETURNS users LANGUAGE plpgsql AS $$ DECLARE r users; BEGIN UPDATE users SET email = p_email, password_hash = p_password_hash, full_name = p_full_name, role = p_role, created_at = p_created_at WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'user % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_user(uuid);
CREATE FUNCTION delete_user(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM users WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_users();
CREATE FUNCTION list_users() RETURNS SETOF users LANGUAGE sql AS $$ SELECT * FROM users ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_cart_item(uuid, uuid, integer);
CREATE FUNCTION create_cart_item(p_user_id uuid, p_product_id uuid, p_quantity integer) RETURNS cart_items LANGUAGE sql AS $$ INSERT INTO cart_items (user_id, product_id, quantity) VALUES (p_user_id, p_product_id, p_quantity) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_cart_item(uuid);
CREATE FUNCTION get_cart_item(p_id uuid) RETURNS SETOF cart_items LANGUAGE sql AS $$ SELECT * FROM cart_items WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_cart_item(uuid, uuid, uuid, integer);
CREATE FUNCTION update_cart_item(p_id uuid, p_user_id uuid, p_product_id uuid, p_quantity integer) RETURNS cart_items LANGUAGE plpgsql AS $$ DECLARE r cart_items; BEGIN UPDATE cart_items SET user_id = p_user_id, product_id = p_product_id, quantity = p_quantity WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'cart_item % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_cart_item(uuid);
CREATE FUNCTION delete_cart_item(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM cart_items WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_cart_items();
CREATE FUNCTION list_cart_items() RETURNS SETOF cart_items LANGUAGE sql AS $$ SELECT * FROM cart_items ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_order(uuid, text, numeric(12,2), text, timestamptz);
CREATE FUNCTION create_order(p_user_id uuid, p_status text, p_total numeric(12,2), p_shipping_address text, p_placed_at timestamptz) RETURNS orders LANGUAGE sql AS $$ INSERT INTO orders (user_id, status, total, shipping_address, placed_at) VALUES (p_user_id, p_status, p_total, p_shipping_address, p_placed_at) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_order(uuid);
CREATE FUNCTION get_order(p_id uuid) RETURNS SETOF orders LANGUAGE sql AS $$ SELECT * FROM orders WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_order(uuid, uuid, text, numeric(12,2), text, timestamptz);
CREATE FUNCTION update_order(p_id uuid, p_user_id uuid, p_status text, p_total numeric(12,2), p_shipping_address text, p_placed_at timestamptz) RETURNS orders LANGUAGE plpgsql AS $$ DECLARE r orders; BEGIN UPDATE orders SET user_id = p_user_id, status = p_status, total = p_total, shipping_address = p_shipping_address, placed_at = p_placed_at WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'order % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_order(uuid);
CREATE FUNCTION delete_order(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM orders WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_orders();
CREATE FUNCTION list_orders() RETURNS SETOF orders LANGUAGE sql AS $$ SELECT * FROM orders ORDER BY id; $$;
DROP FUNCTION IF EXISTS create_order_item(uuid, uuid, integer, numeric(12,2));
CREATE FUNCTION create_order_item(p_order_id uuid, p_product_id uuid, p_quantity integer, p_unit_price numeric(12,2)) RETURNS order_items LANGUAGE sql AS $$ INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (p_order_id, p_product_id, p_quantity, p_unit_price) RETURNING *; $$;
DROP FUNCTION IF EXISTS get_order_item(uuid);
CREATE FUNCTION get_order_item(p_id uuid) RETURNS SETOF order_items LANGUAGE sql AS $$ SELECT * FROM order_items WHERE id = p_id; $$;
DROP FUNCTION IF EXISTS update_order_item(uuid, uuid, uuid, integer, numeric(12,2));
CREATE FUNCTION update_order_item(p_id uuid, p_order_id uuid, p_product_id uuid, p_quantity integer, p_unit_price numeric(12,2)) RETURNS order_items LANGUAGE plpgsql AS $$ DECLARE r order_items; BEGIN UPDATE order_items SET order_id = p_order_id, product_id = p_product_id, quantity = p_quantity, unit_price = p_unit_price WHERE id = p_id RETURNING * INTO r; IF NOT FOUND THEN RAISE EXCEPTION 'order_item % not found', p_id USING ERRCODE = 'P0002'; END IF; RETURN r; END $$;
DROP FUNCTION IF EXISTS delete_order_item(uuid);
CREATE FUNCTION delete_order_item(p_id uuid) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN DELETE FROM order_items WHERE id = p_id; RETURN FOUND; END $$;
DROP FUNCTION IF EXISTS list_order_items();
CREATE FUNCTION list_order_items() RETURNS SETOF order_items LANGUAGE sql AS $$ SELECT * FROM order_items ORDER BY id; $$;
