# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository registry."""
from __future__ import annotations

from .ticket_repository import TicketRepository
from .ticket_comment_repository import TicketCommentRepository
from .user_repository import UserRepository

REPOSITORIES = {
    "entity.ticket": TicketRepository,
    "entity.ticket_comment": TicketCommentRepository,
    "entity.user": UserRepository,
}
