# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.ticket over table `tickets` (database contract)."""
from ...repository import BaseRepository


class TicketRepository(BaseRepository):
    ENTITY_ID = "entity.ticket"
    TABLE = "tickets"
