# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.ticket_comment over table `ticket_comments` (database contract)."""
from ...repository import BaseRepository


class TicketCommentRepository(BaseRepository):
    ENTITY_ID = "entity.ticket_comment"
    TABLE = "ticket_comments"
