# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application services container."""
from __future__ import annotations

from ...service_base import ServiceContext
from .cart_item_service import CartItemService
from .order_service import OrderService
from .product_service import ProductService
from .user_service import UserService


class Services:
    """One attribute per graph service."""

    def __init__(self, ctx: ServiceContext) -> None:
        self.cart_item = CartItemService(ctx)
        self.order = OrderService(ctx)
        self.product = ProductService(ctx)
        self.user = UserService(ctx)


def build_services(ctx: ServiceContext) -> Services:
    return Services(ctx)
