# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application service service.cart_item: one method per graph operation."""
from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Any
from uuid import UUID

from psycopg import sql

from ...engine import ListQuery, Page, Principal
from ...errors import (ConflictError, EntityNotFound, PermissionDenied, ValidationError)
from ...service_base import BaseService
from ...domain.entities.cart_item import CartItem
from ...api.schemas.cart_item import CartItemCreateRequest, CartItemUpdateRequest


class CartItemService(BaseService):
    """Operations of service.cart_item. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""

    def create(self, principal: Principal | None, body: CartItemCreateRequest) -> CartItem:
        """operation.cart_item.create (POST /cart-items) - create"""
        row = self.engine.run("operation.cart_item.create", principal, body=body.model_dump(exclude_unset=True))
        return CartItem.model_validate(row)

    def delete(self, principal: Principal | None, row_id: UUID) -> None:
        """operation.cart_item.delete (DELETE /cart-items/{id}) - delete"""
        self.engine.run("operation.cart_item.delete", principal, row_id=row_id)

    def list(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.cart_item.list (GET /cart-items) - list"""
        page = self.engine.run("operation.cart_item.list", principal, query=query)
        return Page([CartItem.model_validate(r) for r in page.items], page.total)

    def update(self, principal: Principal | None, row_id: UUID, body: CartItemUpdateRequest) -> CartItem:
        """operation.cart_item.update (PATCH /cart-items/{id}) - update"""
        row = self.engine.run("operation.cart_item.update", principal, row_id=row_id, body=body.model_dump(exclude_unset=True))
        return CartItem.model_validate(row)

