# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application service service.order: one method per graph operation."""
from __future__ import annotations

from decimal import Decimal
from typing import Any
from uuid import UUID

from ...engine import ListQuery, Page, Principal
from ...errors import ConflictError
from ...service_base import BaseService
from ...domain.entities.order import Order


class OrderService(BaseService):
    """Operations of service.order. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""

    def list(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.order.list (GET /orders) - list"""
        page = self.engine.run("operation.order.list", principal, query=query)
        return Page([Order.model_validate(r) for r in page.items], page.total)

    def place(self, principal: Principal | None, *, row_id: UUID | None = None, body: dict[str, Any] | None = None, query: ListQuery | None = None) -> Any:
        """operation.order.place (POST /orders) - custom"""
        # handler source: llm (api_implementation)
        body = body or {}
        with self.db.transaction() as conn:
            cart = conn.execute('SELECT "product_id" AS product_id, quantity FROM "cart_items" WHERE "user_id" = %s ORDER BY "product_id" FOR UPDATE', (principal.user_id,)).fetchall()
            if not cart:
                raise ConflictError('The cart is empty', code='CART_EMPTY')
            lines = []
            total = Decimal("0")
            for item in cart:
                product = conn.execute('SELECT id, price, stock FROM "products" WHERE id = %s FOR UPDATE', (item["product_id"],)).fetchone()
                if product is None or item["quantity"] > product["stock"]:
                    raise ConflictError('One or more products are out of stock', code='OUT_OF_STOCK', details={"product_id": str(item["product_id"])})
                lines.append((product["id"], item["quantity"], product["price"]))
                total += product["price"] * item["quantity"]
            order = conn.execute('INSERT INTO "orders" ("user_id", "status", "total", "shipping_address") VALUES (%s, %s, %s, %s) RETURNING *', (principal.user_id, 'pending', total, body.get("shipping_address"))).fetchone()
            for product_id, quantity, price in lines:
                conn.execute('INSERT INTO "order_items" ("order_id", "product_id", quantity, unit_price) VALUES (%s, %s, %s, %s)', (order["id"], product_id, quantity, price))
                conn.execute('UPDATE "products" SET stock = stock - %s WHERE id = %s', (quantity, product_id))
            conn.execute('DELETE FROM "cart_items" WHERE "user_id" = %s', (principal.user_id,))
        return Order.model_validate(order)

    def read(self, principal: Principal | None, row_id: UUID) -> Order:
        """operation.order.read (GET /orders/{id}) - read"""
        return Order.model_validate(self.engine.run("operation.order.read", principal, row_id=row_id))

