# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Application service service.product: one method per graph operation."""
from __future__ import annotations

from uuid import UUID

from ...engine import ListQuery, Page, Principal
from ...service_base import BaseService
from ...domain.entities.product import Product


class ProductService(BaseService):
    """Operations of service.product. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""

    def filter(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.product.filter (GET /products/filter) - list"""
        page = self.engine.run("operation.product.filter", principal, query=query)
        return Page([Product.model_validate(r) for r in page.items], page.total)

    def list(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.product.list (GET /products) - list"""
        page = self.engine.run("operation.product.list", principal, query=query)
        return Page([Product.model_validate(r) for r in page.items], page.total)

    def read(self, principal: Principal | None, row_id: UUID) -> Product:
        """operation.product.read (GET /products/{id}) - read"""
        return Product.model_validate(self.engine.run("operation.product.read", principal, row_id=row_id))

    def search(self, principal: Principal | None, query: ListQuery) -> Page:
        """operation.product.search (GET /products/search) - list"""
        page = self.engine.run("operation.product.search", principal, query=query)
        return Page([Product.model_validate(r) for r in page.items], page.total)

