# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository registry."""
from __future__ import annotations

from .department_repository import DepartmentRepository
from .employee_repository import EmployeeRepository
from .project_repository import ProjectRepository
from .project_member_repository import ProjectMemberRepository
from .task_repository import TaskRepository
from .user_repository import UserRepository

REPOSITORIES = {
    "entity.department": DepartmentRepository,
    "entity.employee": EmployeeRepository,
    "entity.project": ProjectRepository,
    "entity.project_member": ProjectMemberRepository,
    "entity.task": TaskRepository,
    "entity.user": UserRepository,
}
