# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.department over table `departments` (database contract)."""
from ...repository import BaseRepository


class DepartmentRepository(BaseRepository):
    ENTITY_ID = "entity.department"
    TABLE = "departments"
