# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.employee over table `employees` (database contract)."""
from ...repository import BaseRepository


class EmployeeRepository(BaseRepository):
    ENTITY_ID = "entity.employee"
    TABLE = "employees"
