# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.project_member over table `project_members` (database contract)."""
from ...repository import BaseRepository


class ProjectMemberRepository(BaseRepository):
    ENTITY_ID = "entity.project_member"
    TABLE = "project_members"
