# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.project over table `projects` (database contract)."""
from ...repository import BaseRepository


class ProjectRepository(BaseRepository):
    ENTITY_ID = "entity.project"
    TABLE = "projects"
