# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.task over table `tasks` (database contract)."""
from ...repository import BaseRepository


class TaskRepository(BaseRepository):
    ENTITY_ID = "entity.task"
    TABLE = "tasks"
