# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Repository for entity.user over table `users` (database contract)."""
from ...repository import BaseRepository


class UserRepository(BaseRepository):
    ENTITY_ID = "entity.user"
    TABLE = "users"
