"""Backend code generator.

Renders the graph-specific modules (domain entities, API schemas, repositories, services, routes) from a BackendSpec and
copies the static runtime (`runtime/backend_app`). Deterministic: same spec -> byte-identical output.

Every emitted file is recorded in a `FileRecord` with the specification IDs it implements (file_manifest.json).
"""
from __future__ import annotations

import hashlib
import json
import keyword
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from app.analysis.typesys import MAX_PASSWORD, MIN_NEW_PASSWORD, parse_field_type, pydantic_annotation
from app.graph.model import snake_to_pascal

RUNTIME_DIR = Path(__file__).parent / "runtime" / "backend_app"
HEADER = '# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.\n'
PY_TYPES = {"uuid": "UUID", "string": "str", "text": "str", "email": "str", "url": "str", "integer": "int", "decimal": "Decimal",
            "boolean": "bool", "date": "date", "datetime": "datetime", "json": "Any"}


@dataclass
class FileRecord:
    path: str
    kind: str  # generated | runtime | config | test | contract
    source_refs: list[str] = field(default_factory=list)
    sha256: str = ""
    description: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {"path": self.path, "kind": self.kind, "source_refs": sorted(set(self.source_refs)), "sha256": self.sha256, "description": self.description}


class Emitter:
    def __init__(self, root: Path) -> None:
        self.root, self.records = root, []

    def write(self, rel: str, content: str, kind: str, refs: list[str] | None = None, description: str = "") -> None:
        path = self.root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if not content.endswith("\n"):
            content += "\n"
        path.write_text(content, encoding="utf-8")
        self.records.append(FileRecord(rel, kind, list(refs or []), hashlib.sha256(content.encode()).hexdigest(), description))


def ident(name: str) -> str:
    n = re.sub(r"[^0-9a-zA-Z_]", "_", name)
    if n[:1].isdigit():
        n = "v_" + n
    return n + "_" if keyword.iskeyword(n) else n


def enum_member(value: str) -> str:
    return ident(value).upper()


def py_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


# ---------------------------------------------------------------------------------------------------------------------
def render_domain_entity(ent: dict[str, Any]) -> str:
    cls = ent["class_name"]
    lines = [HEADER + f'"""Domain entity {cls} (graph: {ent["id"]}; table: {ent["table"]})."""', "from __future__ import annotations", "",
             "from datetime import date, datetime", "from decimal import Decimal", "from enum import Enum", "from typing import Any, ClassVar", "from uuid import UUID", "",
             "from pydantic import BaseModel, ConfigDict, Field", ""]
    enums = []
    for c in ent["columns"]:
        if c["enum"]:
            ec = cls + snake_to_pascal(c["attr"])
            enums.append((c["attr"], ec))
            lines += ["", f"class {ec}(str, Enum):"] + [f"    {enum_member(v)} = {py_str(v)}" for v in c["enum"]]
    lines += ["", "", f"class {cls}(BaseModel):",
              f'    """Row of `{ent["table"]}` as seen by the domain. Hidden columns are never serialised."""', "",
              '    model_config = ConfigDict(extra="ignore", from_attributes=True)', ""]
    emap = dict(enums)
    for c in ent["columns"]:
        t = emap.get(c["attr"]) or PY_TYPES[c["type"]]
        hidden = c["column"] in ent["hidden_columns"]
        nullable = c["nullable"] or (not c["required"] and c["attr"] != "id")
        ann = f"{t} | None" if nullable else t
        default = " = None" if nullable else ""
        if hidden:
            default = f" = Field({'None' if nullable else '...'}, repr=False, exclude=True)"
        lines.append(f"    {c['attr']}: {ann}{default}")
    lines += ["", f"    TABLE: ClassVar[str] = {py_str(ent['table'])}", f"    GRAPH_ENTITY: ClassVar[str] = {py_str(ent['id'])}"]
    return "\n".join(lines) + "\n"


def _field_decl(f: dict[str, Any], *, request: bool, col: dict[str, Any] | None, enum_name: str | None) -> str:
    ft = parse_field_type(f["type"])
    ann, kw = pydantic_annotation(ft, f.get("enum"), request=request, name=f["name"])
    name = f["name"]
    if request and name == "password":
        ann, kw = "str", [f"max_length={MAX_PASSWORD}", "min_length=1"]
    elif request and name == "new_password":
        ann, kw = "str", [f"max_length={MAX_PASSWORD}", f"min_length={MIN_NEW_PASSWORD}"]
    elif request and name == "reset_token":
        ann, kw = "str", ["max_length=2048", "min_length=1"]
    if ft.base == "decimal":
        ann = "JsonDecimal" if not request else "Decimal"
    if request:
        if f["required"]:
            return f"    {name}: {ann} = Field(..., {', '.join(kw)})" if kw else f"    {name}: {ann}"
        # optional on the wire. If the stored attribute is mandatory, `null` must be rejected (not coerced): keep the plain type.
        non_nullable = bool(col and col["required"])
        typ = ann if non_nullable else f"{ann} | None"
        return f"    {name}: {typ} = Field(None{', ' + ', '.join(kw) if kw else ''})"
    return f"    {name}: {ann}" if f["required"] else f"    {name}: {ann} | None = None"


def render_schemas(spec: dict[str, Any], entity_id: str) -> str:
    ent = spec["entities"][entity_id]
    schemas = [s for s in spec["schemas"].values() if s["entity"] == entity_id]
    cols = {c["attr"]: c for c in ent["columns"]}
    lines = [HEADER + f'"""API request/response models for {ent["id"]} (from api.json schemas)."""', "from __future__ import annotations", "",
             "from datetime import date, datetime", "from decimal import Decimal", "from typing import Any, Literal", "from uuid import UUID", "",
             "from pydantic import BaseModel, ConfigDict, EmailStr, Field", "", "from ...api_common import JsonDecimal", ""]
    auth = spec["auth"]
    for s in sorted(schemas, key=lambda s: s["id"]):
        is_req = s["kind"] == "request"
        lines += ["", "", f"class {s['class_name']}(BaseModel):", f'    """{s["id"]}: {s["name"]}"""', ""]
        lines.append('    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)' if is_req else '    model_config = ConfigDict(from_attributes=True)')
        if not s["fields"]:
            lines.append("    pass")
        for f in s["fields"]:
            lines.append(_field_decl(f, request=is_req, col=cols.get(f["name"]), enum_name=None))
        if is_req:  # server-owned fields: accepted only if equal to the caller, never trusted (see engine._create)
            for op in spec["operations"].values():
                ep = op["endpoint"]
                if ep["request_schema"] == s["id"]:
                    for attr, src in op["params"].get("server_fields", {}).items():
                        if src == "principal.id" and attr not in {f["name"] for f in s["fields"]}:
                            lines.append(f"    {attr}: UUID | None = Field(None, json_schema_extra={{'readOnly': True, 'x-server-owned': True}})")
    if auth and entity_id == auth["entity"] and auth.get("login_response_schema"):
        base = spec["schemas"][auth["login_response_schema"]]["class_name"]
        lines += ["", "", f"class LoginSessionResponse({base}):",
                  '    """Login response satisfying BOTH contracts: the graph\'s user schema (top-level fields) and the Frontend\'s Session {token, user}."""', "",
                  "    token: str", '    token_type: str = "bearer"', "    expires_in: int", f"    user: {base}"]
    for op in spec["operations"].values():
        h = spec["handlers"].get(op["id"])
        if h and h.get("response_extra_fields") and op["entity"] == entity_id:
            resp = spec["schemas"][op["endpoint"]["response_schema"]]["class_name"]
            lines += ["", "", f"class {h['response_class']}({resp}):", f'    """{op["id"]}: additive aggregate fields on top of the graph schema."""', ""]
            for f in h["response_extra_fields"]:
                t = PY_TYPES[f["type"]]
                lines.append(f"    {f['name']}: {t} | None = None")
    return "\n".join(lines) + "\n"


def render_repository(ent: dict[str, Any]) -> str:
    return (HEADER + f'"""Repository for {ent["id"]} over table `{ent["table"]}` (database contract)."""\n'
            "from ...repository import BaseRepository\n\n\n"
            f"class {ent['class_name']}Repository(BaseRepository):\n"
            f"    ENTITY_ID = {py_str(ent['id'])}\n"
            f"    TABLE = {py_str(ent['table'])}\n")


# ---------------------------------------------------------------------------------------------------------------------
def method_name(op: dict[str, Any], taken: set[str]) -> str:
    suffix = op["id"].split(".", 2)[2]
    name = ident(suffix.replace(".", "_"))
    if name in taken:
        name = ident(op["id"].replace(".", "_"))
    taken.add(name)
    return name


def service_key(service_id: str) -> str:
    return service_id.split(".", 1)[1]


def _group_by_service(spec: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = {}
    for op in spec["operations"].values():
        out.setdefault(op["service"], []).append(op)
    return {k: sorted(v, key=lambda o: o["id"]) for k, v in sorted(out.items())}


def render_service(spec: dict[str, Any], service_id: str, ops: list[dict[str, Any]], names: dict[str, str]) -> str:
    key = service_key(service_id)
    cls = snake_to_pascal(key) + "Service"
    ents = sorted({o["entity"] for o in ops if o["entity"]})
    imports = [HEADER + f'"""Application service {service_id}: one method per graph operation."""', "from __future__ import annotations", "",
               "from datetime import date, datetime, timezone", "from decimal import Decimal", "from typing import Any", "from uuid import UUID", "",
               "from psycopg import sql", "",
               "from ...engine import ListQuery, Page, Principal", "from ...errors import (ConflictError, EntityNotFound, PermissionDenied, ValidationError)",
               "from ...service_base import BaseService"]
    for e in ents:
        k = spec["entities"][e]["key"]
        imports.append(f"from ...domain.entities.{k} import {spec['entities'][e]['class_name']}")
    schema_imports: dict[str, list[str]] = {}
    for o in ops:
        s = o["endpoint"]["request_schema"]
        if s:
            ent = spec["schemas"][s]["entity"]
            schema_imports.setdefault(spec["entities"][ent]["key"], []).append(spec["schemas"][s]["class_name"])
    for k, names_ in sorted(schema_imports.items()):
        imports.append(f"from ...api.schemas.{k} import {', '.join(sorted(set(names_)))}")
    lines = imports + ["", "", f"class {cls}(BaseService):", f'    """Operations of {service_id}. Business rules live in the engine/rules, driven by the graph; routes only delegate here."""', ""]
    for o in ops:
        m = names[o["id"]]
        eid = o["entity"]
        dom = spec["entities"][eid]["class_name"] if eid else "dict"
        req = spec["schemas"][o["endpoint"]["request_schema"]]["class_name"] if o["endpoint"]["request_schema"] else None
        kind, oid = o["kind"], o["id"]
        doc = f'        """{oid} ({o["endpoint"]["method"]} {o["endpoint"]["path"]}) - {o["kind"]}"""'
        if kind == "create":
            lines += [f"    def {m}(self, principal: Principal | None, body: {req}) -> {dom}:", doc,
                      f"        row = self.engine.run({py_str(oid)}, principal, body=body.model_dump(exclude_unset=True))", f"        return {dom}.model_validate(row)", ""]
        elif kind == "read":
            lines += [f"    def {m}(self, principal: Principal | None, row_id: UUID) -> {dom}:", doc,
                      f"        return {dom}.model_validate(self.engine.run({py_str(oid)}, principal, row_id=row_id))", ""]
        elif kind == "list":
            lines += [f"    def {m}(self, principal: Principal | None, query: ListQuery) -> Page:", doc,
                      f"        page = self.engine.run({py_str(oid)}, principal, query=query)",
                      f"        return Page([{dom}.model_validate(r) for r in page.items], page.total)", ""]
        elif kind in ("update", "transition"):
            lines += [f"    def {m}(self, principal: Principal | None, row_id: UUID, body: {req}) -> {dom}:", doc,
                      f"        row = self.engine.run({py_str(oid)}, principal, row_id=row_id, body=body.model_dump(exclude_unset=True))",
                      f"        return {dom}.model_validate(row)", ""]
        elif kind == "delete":
            lines += [f"    def {m}(self, principal: Principal | None, row_id: UUID) -> None:", doc,
                      f"        self.engine.run({py_str(oid)}, principal, row_id=row_id)", ""]
        elif kind == "auth.login":
            lines += [f"    def {m}(self, body: {req}, client: str) -> dict[str, Any]:", doc, "        return self.ctx.auth.login(body.email, body.password, client)", ""]
        elif kind == "auth.logout":
            lines += [f"    def {m}(self, principal: Principal) -> None:", doc, "        self.ctx.auth.logout(principal)", ""]
        elif kind == "auth.request_password_reset":
            lines += [f"    def {m}(self, body: {req}, client: str) -> None:", doc, "        self.ctx.auth.request_password_reset(body.email, client)", ""]
        elif kind == "auth.reset_password":
            lines += [f"    def {m}(self, body: {req}, client: str) -> None:", doc, "        self.ctx.auth.reset_password(body.reset_token, body.new_password, client)", ""]
        else:  # custom / aggregate
            h = spec["handlers"].get(oid)
            lines.append(f"    def {m}(self, principal: Principal | None, *, row_id: UUID | None = None, body: dict[str, Any] | None = None, query: ListQuery | None = None) -> Any:")
            lines.append(doc)
            if h and h.get("status") == "implemented":
                lines.append(f"        # handler source: {h.get('source', 'llm')} ({h.get('stage', 'api_implementation')})")
                lines += ["        " + ln if ln.strip() else "" for ln in h["code"].rstrip().splitlines()]
            else:
                lines.append(f"        return self.not_implemented({py_str(oid)})")
            lines.append("")
    return "\n".join(lines) + "\n"


def _path_sort_key(path: str) -> tuple:
    return tuple((1, "") if seg.startswith("{") else (0, seg) for seg in path.strip("/").split("/"))


def _py_query_type(q: dict[str, Any]) -> str:
    if q["enum"]:
        return "Literal[" + ", ".join(py_str(v) for v in q["enum"]) + "]"
    return PY_TYPES[q["type"]]


def render_routes(spec: dict[str, Any], service_id: str, ops: list[dict[str, Any]], names: dict[str, str]) -> str:
    key = service_key(service_id)
    ents = sorted({o["entity"] for o in ops if o["entity"]})
    head = [HEADER + f'"""HTTP routes for {service_id}. Route handlers only delegate to the application service."""', "from __future__ import annotations", "",
            "from datetime import date, datetime", "from decimal import Decimal", "from typing import Any, Literal", "from uuid import UUID", "",
            "from fastapi import APIRouter, Depends, Query, Request, Response", "",
            "from ...api_common import error_responses", "from ...auth import authorize", "from ...engine import ListQuery, Principal",
            "from ..deps import get_services", "from ...application.services import Services"]
    schema_imports: dict[str, set[str]] = {}
    for o in ops:
        ep = o["endpoint"]
        for sid in (ep["request_schema"], ep["response_schema"]):
            if sid:
                schema_imports.setdefault(spec["entities"][spec["schemas"][sid]["entity"]]["key"], set()).add(spec["schemas"][sid]["class_name"])
        h = spec["handlers"].get(o["id"])
        if h and h.get("response_class") and o["entity"]:
            schema_imports.setdefault(spec["entities"][o["entity"]]["key"], set()).add(h["response_class"])
        if o["kind"] == "auth.login":
            schema_imports.setdefault(spec["entities"][o["entity"]]["key"], set()).add("LoginSessionResponse")
    for k, n in sorted(schema_imports.items()):
        head.append(f"from ..schemas.{k} import {', '.join(sorted(n))}")
    lines = head + ["", f"router = APIRouter(tags=[{py_str(key)}])", ""]
    for o in sorted(ops, key=lambda o: (_path_sort_key(o["endpoint"]["path"]), o["endpoint"]["method"])):
        ep, oid = o["endpoint"], o["id"]
        m = names[oid]
        kind = o["kind"]
        resp_cls = None
        if ep["response_schema"]:
            resp_cls = spec["schemas"][ep["response_schema"]]["class_name"]
        h = spec["handlers"].get(oid)
        if h and h.get("response_class"):
            resp_cls = h["response_class"]
        if kind == "auth.login":
            resp_cls = "LoginSessionResponse"
        many = o["cardinality"] == "many"
        resp_model = "None" if (ep["status_code"] == 204 or not resp_cls) else (f"list[{resp_cls}]" if many else resp_cls)
        params = ["request: Request"]
        call_args = ["principal"]
        if kind.startswith("auth."):
            call_args = []
        if "id" in ep["path_params"]:
            params.append("id: UUID")
        if ep["request_schema"]:
            params.append(f"body: {spec['schemas'][ep['request_schema']]['class_name']}")
        is_list = kind == "list" or (kind == "aggregate" and many)
        if is_list:
            params.append("response: Response")
            for q in ep["query_params"]:
                if q["kind"] == "filter":
                    params.append(f"{q['name']}: {_py_query_type(q)} | None = None")
                else:
                    params.append("query: str | None = Query(None, max_length=200, description=\"Case-insensitive text search\")")
            params += ["limit: int = Query(100, ge=1, le=1000)", "offset: int = Query(0, ge=0)",
                       "sort: str | None = Query(None, max_length=64, description=\"Attribute to sort by\")",
                       "order: Literal['asc', 'desc'] = Query('asc')"]
        auth_dep = "Depends(authorize(" + py_str(oid) + "))"
        public = o["access"] == "public"
        params.append(f"principal: Principal | None = {auth_dep}" if not public else f"principal: None = {auth_dep}")
        params.append("services: Services = Depends(get_services)")
        svc = f"services.{key}.{m}"
        client = "request.client.host if request.client else 'unknown'"
        body = []
        if kind.startswith("auth."):
            args = []
            if ep["request_schema"]:
                args.append("body")
            if kind != "auth.logout":
                args.append(client)
            else:
                args = ["principal"]
            call = f"{svc}({', '.join(args)})"
            body = [f"    return {call}"] if ep["status_code"] != 204 else [f"    {call}", "    return Response(status_code=204)"]
        elif kind in ("create",):
            body = [f"    return {svc}(principal, body)"]
        elif kind in ("read",):
            body = [f"    return {svc}(principal, id)"]
        elif kind in ("update", "transition"):
            body = [f"    return {svc}(principal, id, body)"]
        elif kind == "delete":
            body = [f"    {svc}(principal, id)", "    return Response(status_code=204)"]
        elif kind == "list":
            filt = ", ".join(f"{q['name']!r}: {q['name']}" for q in ep["query_params"] if q["kind"] == "filter")
            qarg = "query" if any(q["kind"] == "search" for q in ep["query_params"]) else "None"
            body = [f"    page = {svc}(principal, ListQuery(filters={{{filt}}}, search={qarg}, sort=sort, order=order, limit=limit, offset=offset))",
                    "    response.headers['X-Total-Count'] = str(page.total)", "    return page.items"]
        else:  # custom / aggregate
            kw = []
            if "id" in ep["path_params"]:
                kw.append("row_id=id")
            if ep["request_schema"]:
                kw.append("body=body.model_dump(exclude_unset=True)")
            if is_list:
                filt = ", ".join(f"{q['name']!r}: {q['name']}" for q in ep["query_params"] if q["kind"] == "filter")
                kw.append(f"query=ListQuery(filters={{{filt}}}, sort=sort, order=order, limit=limit, offset=offset)")
            call = f"{svc}(principal{', ' if kw else ''}{', '.join(kw)})"
            if ep["status_code"] == 204:
                body = [f"    {call}", "    return Response(status_code=204)"]
            elif many:
                body = [f"    result = {call}", "    items = result.items if hasattr(result, 'items') and not isinstance(result, dict) else result",
                        "    if hasattr(result, 'total'):", "        response.headers['X-Total-Count'] = str(result.total)", "    return items"]
            else:
                body = [f"    return {call}"]
        desc = (o["description"] or o["name"]) + f"\n\nOperation `{oid}`. Access: {o['access']}" + (f" ({', '.join(r.split('.', 1)[1] for r in o['roles'])})" if o["roles"] else "") + "."
        if o["notes"]:
            desc += " Note: " + "; ".join(o["notes"])
        er = (f"error_responses(authenticated={not public}, restricted={o['access'] == 'restricted'}, has_path_id={'id' in ep['path_params']}, "
              f"mutating={ep['method'] != 'GET'}, rate_limited={kind.startswith('auth.') and public})")
        lines += [
            f"@router.{ep['method'].lower()}({py_str(ep['path'])}, operation_id={py_str(ep['id'])}, summary={py_str(o['name'])}, description={py_str(desc)},",
            f"    response_model={resp_model}, status_code={ep['status_code']}, responses={er}" + (", response_class=Response" if ep["status_code"] == 204 else "") + ")",
            f"def {ident(ep['id'].replace('.', '_'))}({', '.join(params)}):"] + body + [""]
    return "\n".join(lines) + "\n"


def render_services_init(spec: dict[str, Any], groups: dict[str, list[dict[str, Any]]]) -> str:
    lines = [HEADER + '"""Application services container."""', "from __future__ import annotations", "", "from ...service_base import ServiceContext"]
    for sid in groups:
        k = service_key(sid)
        lines.append(f"from .{k}_service import {snake_to_pascal(k)}Service")
    lines += ["", "", "class Services:", '    """One attribute per graph service."""', "", "    def __init__(self, ctx: ServiceContext) -> None:"]
    lines += [f"        self.{service_key(sid)} = {snake_to_pascal(service_key(sid))}Service(ctx)" for sid in groups] or ["        pass"]
    lines += ["", "", "def build_services(ctx: ServiceContext) -> Services:", "    return Services(ctx)"]
    return "\n".join(lines) + "\n"


def render_routes_init(groups: dict[str, list[dict[str, Any]]]) -> str:
    lines = [HEADER + '"""All routers combined into one, routes ordered most-specific first.', "",
             'FastAPI matches in registration order, so `/tasks/assigned` must precede `/tasks/{id}`; sorting globally guarantees it."""',
             "from __future__ import annotations", "", "from fastapi import APIRouter", ""]
    for sid in groups:
        k = service_key(sid)
        lines.append(f"from .{k} import router as {k}_router")
    lines += ["", "", "def _key(route) -> tuple:", '    segs = route.path.strip("/").split("/")', "    return tuple((1, '') if s.startswith('{') else (0, s) for s in segs)", "",
              "", "api_router = APIRouter()", "_routes = [r for rt in [" + ", ".join(f"{service_key(s)}_router" for s in groups) + "] for r in rt.routes]",
              "api_router.routes.extend(sorted(_routes, key=lambda r: (_key(r), sorted(getattr(r, 'methods', []) or []))))", "", "ROUTERS = [api_router]"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------------------------------------------------
def generate_backend(spec: dict[str, Any], out_dir: Path, *, db_contract_dir: Path | None = None, openapi_ready: bool = True) -> list[FileRecord]:
    """Write the backend project into `out_dir` (the `backend_app` package + project files)."""
    out = Path(out_dir)
    pkg = out / spec["project"]["package"]
    if pkg.exists():
        shutil.rmtree(pkg)  # generated tree is owned by the agent; hand-written files live outside the package
    em = Emitter(out)
    pk = spec["project"]["package"]

    # static runtime (agent infrastructure)
    for src in sorted(RUNTIME_DIR.rglob("*")):
        if src.is_file() and "__pycache__" not in src.parts and src.suffix in (".py", ".json", ".md", ""):
            rel = f"{pk}/{src.relative_to(RUNTIME_DIR).as_posix()}"
            if rel.endswith("generated/spec.json"):
                continue
            em.write(rel, src.read_text(encoding="utf-8"), "runtime", [], "static runtime (agent infrastructure)")
    em.write(f"{pk}/generated/__init__.py", HEADER, "generated", [], "package marker")
    em.write(f"{pk}/generated/spec.json", json.dumps(spec, indent=2, sort_keys=True), "generated",
             [spec["project"]["id"]] + sorted(spec["operations"]) + sorted(spec["entities"]), "the resolved BackendSpec interpreted by the runtime")

    groups = _group_by_service(spec)
    names: dict[str, str] = {}
    for sid, ops in groups.items():
        taken: set[str] = set()
        for o in ops:
            names[o["id"]] = method_name(o, taken)

    for eid, ent in sorted(spec["entities"].items()):
        k = ent["key"]
        em.write(f"{pk}/domain/entities/{k}.py", render_domain_entity(ent), "generated", [eid, f"table:{ent['table']}"], f"domain entity {ent['class_name']}")
        refs = [eid] + sorted(s["id"] for s in spec["schemas"].values() if s["entity"] == eid)
        em.write(f"{pk}/api/schemas/{k}.py", render_schemas(spec, eid), "generated", refs, f"request/response models for {eid}")
        em.write(f"{pk}/infrastructure/repositories/{k}_repository.py", render_repository(ent), "generated", [eid, f"table:{ent['table']}"], f"repository for {eid}")
    for pkgdir in ("domain/entities", "api/schemas"):
        em.write(f"{pk}/{pkgdir}/__init__.py", HEADER, "generated", [], "package marker")
    repo_init = [HEADER + '"""Repository registry."""', "from __future__ import annotations", ""]
    repo_init += [f"from .{e['key']}_repository import {e['class_name']}Repository" for e in spec["entities"].values()]
    repo_init += ["", "REPOSITORIES = {"] + [f"    {py_str(eid)}: {e['class_name']}Repository," for eid, e in sorted(spec["entities"].items())] + ["}"]
    em.write(f"{pk}/infrastructure/repositories/__init__.py", "\n".join(repo_init), "generated", sorted(spec["entities"]), "repository registry")
    em.write(f"{pk}/infrastructure/__init__.py", HEADER, "generated", [], "package marker")

    for sid, ops in groups.items():
        k = service_key(sid)
        op_ids = [o["id"] for o in ops]
        refs = [sid] + op_ids + sorted({o["endpoint"]["id"] for o in ops}) + [r["id"] for r in spec["rules"] if set(r["operations"]) & set(op_ids)]
        em.write(f"{pk}/application/services/{k}_service.py", render_service(spec, sid, ops, names), "generated", refs, f"application service {sid}")
        em.write(f"{pk}/api/routes/{k}.py", render_routes(spec, sid, ops, names), "generated",
                 refs + [p for o in ops for p in (o["endpoint"]["request_schema"], o["endpoint"]["response_schema"]) if p], f"HTTP routes for {sid}")
    em.write(f"{pk}/application/services/__init__.py", render_services_init(spec, groups), "generated", list(groups), "services container")
    em.write(f"{pk}/application/__init__.py", HEADER, "generated", [], "package marker")
    em.write(f"{pk}/api/routes/__init__.py", render_routes_init(groups), "generated", sorted(spec["operations"]), "route registry (ordered)")
    for sub in ("api/__init__.py",):
        em.write(f"{pk}/{sub}", HEADER, "generated", [], "package marker")
    em.write(f"{pk}/api/deps.py", HEADER + '"""FastAPI dependencies."""\nfrom __future__ import annotations\n\nfrom fastapi import Request\n\nfrom ..application.services import Services\n\n\n'
             'def get_services(request: Request) -> Services:\n    return request.app.state.container.services\n', "runtime", [], "service dependency")

    # project files
    em.write("pyproject.toml", render_pyproject(spec), "config", [spec["project"]["id"]], "project metadata and dependencies")
    em.write(".env.example", render_env_example(spec), "config", [], "environment variable template")
    em.write(".gitignore", ".env\n__pycache__/\n.pytest_cache/\n", "config", [], "")
    if db_contract_dir is not None:
        for f in sorted(Path(db_contract_dir).glob("*")):
            if f.is_file():
                em.write(f"db_contract/{f.name}", f.read_text(encoding="utf-8"), "contract", [f"database:{f.name}"], "copy of the Database Agent contract the backend was built against")
    return em.records


def render_pyproject(spec: dict[str, Any]) -> str:
    return f'''[project]
name = "{spec["project"]["key"].replace("_", "-")}-backend"
version = "0.1.0"
description = "Generated backend for {spec["project"]["name"]}"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.110", "pydantic>=2.5", "email-validator>=2.0", "psycopg[binary,pool]>=3.1", "pyjwt>=2.8", "uvicorn>=0.27",
]

[project.optional-dependencies]
test = ["pytest>=8", "httpx>=0.27"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "-q"
markers = ["integration: needs a real PostgreSQL"]
'''


def render_env_example(spec: dict[str, Any]) -> str:
    return f"""# Copy to .env (never commit real values)
APP_ENV=development                      # production/staging enforce JWT_SECRET and explicit CORS origins
DATABASE_URL=postgresql://USER:PASSWORD@localhost:5432/DBNAME
DATABASE_SCHEMA={spec["project"]["key"]}   # schema created by the Database Agent
LOG_LEVEL=INFO
JWT_SECRET=                              # >= 32 random characters in production
ACCESS_TOKEN_TTL_MINUTES=60
CORS_ORIGINS=http://localhost:5173       # the Frontend dev origin; list explicit origins, never '*'
DB_POOL_MIN=1
DB_POOL_MAX=10
MAX_BODY_BYTES=1048576
RATE_LIMIT_PER_MINUTE=20
LLM_PROVIDER=mock                        # only used by the Backend Agent itself, not by the generated service
"""
