# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity CartItem (graph: entity.cart_item; table: cart_items)."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field



class CartItem(BaseModel):
    """Row of `cart_items` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    user_id: UUID
    product_id: UUID
    quantity: int

    TABLE: ClassVar[str] = "cart_items"
    GRAPH_ENTITY: ClassVar[str] = "entity.cart_item"
