# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity Category (graph: entity.category; table: categories)."""
from __future__ import annotations

from typing import ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Category(BaseModel):
    """Row of `categories` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    name: str

    TABLE: ClassVar[str] = "categories"
    GRAPH_ENTITY: ClassVar[str] = "entity.category"
