# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity Category (graph: entity.category; table: categories)."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field



class Category(BaseModel):
    """Row of `categories` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    name: str

    TABLE: ClassVar[str] = "categories"
    GRAPH_ENTITY: ClassVar[str] = "entity.category"
