# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity OrderItem (graph: entity.order_item; table: order_items)."""
from __future__ import annotations

from decimal import Decimal
from typing import ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class OrderItem(BaseModel):
    """Row of `order_items` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    order_id: UUID
    product_id: UUID
    quantity: int
    unit_price: Decimal

    TABLE: ClassVar[str] = "order_items"
    GRAPH_ENTITY: ClassVar[str] = "entity.order_item"
