# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity Order (graph: entity.order; table: orders)."""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class OrderStatus(str, Enum):
    PENDING = "pending"
    PAID = "paid"
    SHIPPED = "shipped"
    DELIVERED = "delivered"
    CANCELLED = "cancelled"


class Order(BaseModel):
    """Row of `orders` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    user_id: UUID
    status: OrderStatus
    total: Decimal
    shipping_address: str | None = None
    placed_at: datetime | None = None

    TABLE: ClassVar[str] = "orders"
    GRAPH_ENTITY: ClassVar[str] = "entity.order"
