# GENERATED by the Backend Agent from the project graphs. Do not edit by hand: regenerate instead.
"""Domain entity Product (graph: entity.product; table: products)."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field



class Product(BaseModel):
    """Row of `products` as seen by the domain. Hidden columns are never serialised."""

    model_config = ConfigDict(extra="ignore", from_attributes=True)

    id: UUID
    name: str
    description: str | None = None
    price: Decimal
    stock: int
    category_id: UUID | None = None
    image_url: str | None = None

    TABLE: ClassVar[str] = "products"
    GRAPH_ENTITY: ClassVar[str] = "entity.product"
